/**
 * The account screens' text, in English and Brazilian Portuguese.
 *
 * The rest of the app is English-only, so there is no shared translation layer to join: this
 * is the smallest one that serves these screens, chosen from the OS language
 * (`navigator.language`) once per render. Adding a language is adding one `Record<Key, string>`.
 * A missing key is a compile error in the second table, so the two cannot drift.
 *
 * Messages for failures are **generic by design** (ADR-0029 SR-10): they never say whether an
 * address is registered, never echo a value, and never show the CLI's own text, which carries
 * the command line and so the address.
 */

import { CODE_LENGTH, PASSWORD_MAX_CHARS, PASSWORD_MIN_CHARS } from '../../shared/accountRules.js';

const en = {
  // shell
  'account.loading': 'Checking your account…',
  'account.tab': 'Account',
  'account.avatar': 'Account: {who}',
  'account.signedOutAvatar': 'Sign in',
  // sign-in
  'signin.title': 'Sign in to dev-team-agents',
  'signin.lead': 'An account is needed to use the app. Choose how to sign in.',
  'signin.google': 'Continue with Google',
  'signin.github': 'Continue with GitHub',
  'signin.browserWaiting': 'Finish signing in in your browser. This window waits up to five minutes.',
  'signin.or': 'or use your email',
  'signin.tabCode': 'Email code',
  'signin.tabPassword': 'Email and password',
  'signin.email': 'Email address',
  'signin.sendCode': 'Send me a code',
  'signin.codeSentTo': 'If {email} can sign in, a code was sent to it. It is valid for 10 minutes.',
  'signin.code': 'Code',
  'signin.codeHelp': '8 digits',
  'signin.verify': 'Sign in',
  'signin.useAnotherEmail': 'Use another address',
  'signin.password': 'Password',
  'signin.signIn': 'Sign in',
  'signin.forgot': 'Forgot your password?',
  'signin.createAccount': 'Create an account',
  'signin.haveAccount': 'I already have an account',
  'signin.name': 'Name (optional)',
  'signin.newPassword': 'Choose a password',
  'signin.passwordHelp': '10 to 64 characters.',
  'signin.signUp': 'Create account',
  'signin.confirmEmail': 'Confirm your email',
  'signin.confirmLead': 'If {email} can sign up, a confirmation code was sent to it. Enter it to finish.',
  'signin.confirm': 'Confirm and sign in',
  'signin.cancel': 'Cancel',
  'signin.back': 'Back',
  'signin.working': 'Working…',
  // forgot
  'forgot.title': 'Reset your password',
  'forgot.lead': 'We will send a code to your email address.',
  'forgot.send': 'Send the code',
  'forgot.codeLead': 'If {email} can sign in, a recovery code was sent to it.',
  'forgot.finish': 'Set the new password',
  'forgot.newPassword': 'New password',
  // blocked
  'blocked.title.trial_expired': 'Your trial has ended',
  'blocked.title.banned': 'This account is blocked',
  'blocked.title.needs_online_check': 'A connection is needed to check your account',
  'blocked.title.invalid': 'Your license could not be verified',
  'blocked.title.signed_out': 'You are signed out',
  'blocked.title.error': 'Your account could not be checked',
  'blocked.body.trial_expired': 'Your free trial is over, so the app is paused for this account.',
  'blocked.body.banned': 'This account cannot use the app.',
  'blocked.body.needs_online_check': 'The app has not been able to confirm your license for a while. Connect to the internet and check again.',
  'blocked.body.invalid': 'The saved license on this machine is not valid. Check again, or sign out and sign in once more.',
  'blocked.body.signed_out': 'Sign in to continue.',
  'blocked.body.error': 'Try again in a moment.',
  'blocked.untouched': 'Your projects and files are untouched.',
  'blocked.check': 'Check again',
  'blocked.signOut': 'Sign out',
  'blocked.signedInAs': 'Signed in as {who}',
  // banner (warn mode)
  'banner.title.trial_expired': 'Your trial has ended',
  'banner.title.banned': 'This account is blocked',
  'banner.title.needs_online_check': 'Your account needs an online check',
  'banner.title.invalid': 'Your license could not be verified',
  'banner.title.signed_out': 'You are not signed in',
  'banner.title.error': 'Your account could not be checked',
  'banner.body': 'You can keep working for now, but this will stop being allowed.',
  'banner.open': 'Open account',
  'banner.signIn': 'Sign in',
  'banner.dismiss': 'Dismiss',
  // profile
  'profile.title': 'Your account',
  'profile.loadFailed': 'Your profile could not be loaded.',
  'profile.retry': 'Try again',
  'profile.name': 'Display name',
  'profile.saveName': 'Save name',
  'profile.nameSaved': 'Name saved.',
  'profile.email': 'Email address',
  'profile.changeEmail': 'Change email',
  'profile.newEmail': 'New email address',
  'profile.emailSent': 'A code was sent to {email} and to your current address.',
  'profile.codeNew': 'Code sent to the new address',
  'profile.codeCurrent': 'Code sent to the current address (if you received one)',
  'profile.confirmEmail': 'Confirm the change',
  'profile.emailChanged': 'Email changed.',
  'profile.emailWaiting': 'Waiting for the other address. Enter its code to finish.',
  'profile.pendingEmail': 'A change to {email} is waiting for confirmation.',
  'profile.identities': 'Sign-in methods',
  'profile.link': 'Link {provider}',
  'profile.unlink': 'Unlink {provider}',
  'profile.unlinkConfirm': 'Click again to unlink {provider}',
  'profile.providerEmail': 'Email',
  'profile.linked': '{provider} linked.',
  'profile.unlinked': '{provider} unlinked.',
  'profile.password': 'Password',
  'profile.changePassword': 'Change password',
  'profile.currentPassword': 'Current password',
  'profile.newPassword': 'New password',
  'profile.passwordChanged': 'Password changed. Other devices were signed out.',
  'profile.passwordChangedPartial': 'Password changed. Other devices could not be signed out; do it from them.',
  'profile.signOut': 'Sign out',
  'profile.signedOutLocalOnly': 'Signed out on this computer. The server could not be reached to end the session there.',
  'profile.signedOut': 'Signed out.',
  'profile.license': 'License',
  'profile.license.active': 'Active',
  'profile.license.trial': 'Trial',
  'profile.license.trialEnds': 'Trial ends {date}',
  'profile.insecureStore': 'This machine keeps your session in a plain file because no secure store was available.',
  // delete
  'delete.title': 'Delete account',
  'delete.lead': 'This permanently deletes your account and license. It cannot be undone.',
  'delete.start': 'Delete my account…',
  'delete.confirmWord': 'Type {word} to confirm',
  'delete.sendCode': 'Send a confirmation code',
  'delete.codeSent': 'A confirmation code was sent to your email address.',
  'delete.code': 'Confirmation code',
  'delete.confirm': 'Delete account permanently',
  'delete.done': 'Your account was deleted.',
  'delete.cancel': 'Cancel',
  // fields
  'field.required': 'This field is required.',
  'field.email-invalid': 'That does not look like an email address.',
  'field.code-invalid': 'The code is {digits} digits.',
  'field.password-length': 'The password must be {min} to {max} characters.',
  'field.name-invalid': 'The name must be 1 to 80 characters and cannot start with a dash.',
  'field.unsafe-text': 'That text contains characters that cannot be used.',
  'field.show': 'Show',
  'field.hide': 'Hide',
  // errors (generic)
  'error.invalid_credentials': 'The email or password is not correct.',
  'error.invalid_code': 'That code is not valid or has expired.',
  'error.session_expired': 'Your session ended. Sign in again.',
  'error.not_signed_in': 'You are not signed in.',
  'error.rate_limited': 'Too many attempts. Wait a moment and try again.',
  'error.unreachable': 'The account server could not be reached. Check your connection and try again.',
  'error.not_configured': 'This build of the app cannot sign in to an account.',
  'error.headless': 'No browser is available on this machine. Sign in with an email code instead.',
  'error.timeout': 'The sign-in took too long. Try again.',
  'error.oauth_failed': 'The sign-in in the browser did not complete. Try again.',
  'error.password_rejected': 'That password was not accepted.',
  'error.last_identity': 'This is your only way to sign in, so it cannot be removed. Link another method first.',
  'error.refused': 'Check the values and try again.',
  'error.unavailable': 'The devteam command could not be run.',
  'error.generic': 'Something went wrong. Try again.',
} as const;

export type StringKey = keyof typeof en;

const ptBR: Record<StringKey, string> = {
  'account.loading': 'Verificando sua conta…',
  'account.tab': 'Conta',
  'account.avatar': 'Conta: {who}',
  'account.signedOutAvatar': 'Entrar',
  'signin.title': 'Entre no dev-team-agents',
  'signin.lead': 'É preciso ter uma conta para usar o app. Escolha como entrar.',
  'signin.google': 'Continuar com o Google',
  'signin.github': 'Continuar com o GitHub',
  'signin.browserWaiting': 'Conclua a entrada no navegador. Esta janela espera até cinco minutos.',
  'signin.or': 'ou use seu e-mail',
  'signin.tabCode': 'Código por e-mail',
  'signin.tabPassword': 'E-mail e senha',
  'signin.email': 'Endereço de e-mail',
  'signin.sendCode': 'Enviar um código',
  'signin.codeSentTo': 'Se {email} puder entrar, um código foi enviado a ele. Vale por 10 minutos.',
  'signin.code': 'Código',
  'signin.codeHelp': '8 dígitos',
  'signin.verify': 'Entrar',
  'signin.useAnotherEmail': 'Usar outro endereço',
  'signin.password': 'Senha',
  'signin.signIn': 'Entrar',
  'signin.forgot': 'Esqueceu a senha?',
  'signin.createAccount': 'Criar uma conta',
  'signin.haveAccount': 'Já tenho uma conta',
  'signin.name': 'Nome (opcional)',
  'signin.newPassword': 'Escolha uma senha',
  'signin.passwordHelp': '10 a 64 caracteres.',
  'signin.signUp': 'Criar conta',
  'signin.confirmEmail': 'Confirme seu e-mail',
  'signin.confirmLead': 'Se {email} puder se cadastrar, um código de confirmação foi enviado a ele. Digite-o para concluir.',
  'signin.confirm': 'Confirmar e entrar',
  'signin.cancel': 'Cancelar',
  'signin.back': 'Voltar',
  'signin.working': 'Aguarde…',
  'forgot.title': 'Redefinir a senha',
  'forgot.lead': 'Vamos enviar um código para o seu e-mail.',
  'forgot.send': 'Enviar o código',
  'forgot.codeLead': 'Se {email} puder entrar, um código de recuperação foi enviado a ele.',
  'forgot.finish': 'Definir a nova senha',
  'forgot.newPassword': 'Nova senha',
  'blocked.title.trial_expired': 'Seu período de teste terminou',
  'blocked.title.banned': 'Esta conta está bloqueada',
  'blocked.title.needs_online_check': 'É preciso conexão para verificar sua conta',
  'blocked.title.invalid': 'Não foi possível verificar sua licença',
  'blocked.title.signed_out': 'Você saiu da conta',
  'blocked.title.error': 'Não foi possível verificar sua conta',
  'blocked.body.trial_expired': 'Seu teste gratuito acabou, então o app está pausado para esta conta.',
  'blocked.body.banned': 'Esta conta não pode usar o app.',
  'blocked.body.needs_online_check': 'O app não consegue confirmar sua licença há algum tempo. Conecte-se à internet e verifique de novo.',
  'blocked.body.invalid': 'A licença salva nesta máquina não é válida. Verifique de novo, ou saia e entre mais uma vez.',
  'blocked.body.signed_out': 'Entre para continuar.',
  'blocked.body.error': 'Tente de novo em instantes.',
  'blocked.untouched': 'Seus projetos e arquivos continuam intactos.',
  'blocked.check': 'Verificar de novo',
  'blocked.signOut': 'Sair',
  'blocked.signedInAs': 'Conectado como {who}',
  'banner.title.trial_expired': 'Seu período de teste terminou',
  'banner.title.banned': 'Esta conta está bloqueada',
  'banner.title.needs_online_check': 'Sua conta precisa de uma verificação online',
  'banner.title.invalid': 'Não foi possível verificar sua licença',
  'banner.title.signed_out': 'Você não está conectado',
  'banner.title.error': 'Não foi possível verificar sua conta',
  'banner.body': 'Você pode continuar por enquanto, mas isso deixará de ser permitido.',
  'banner.open': 'Abrir a conta',
  'banner.signIn': 'Entrar',
  'banner.dismiss': 'Dispensar',
  'profile.title': 'Sua conta',
  'profile.loadFailed': 'Não foi possível carregar seu perfil.',
  'profile.retry': 'Tentar de novo',
  'profile.name': 'Nome de exibição',
  'profile.saveName': 'Salvar nome',
  'profile.nameSaved': 'Nome salvo.',
  'profile.email': 'Endereço de e-mail',
  'profile.changeEmail': 'Alterar e-mail',
  'profile.newEmail': 'Novo endereço de e-mail',
  'profile.emailSent': 'Um código foi enviado para {email} e para o seu endereço atual.',
  'profile.codeNew': 'Código enviado ao novo endereço',
  'profile.codeCurrent': 'Código enviado ao endereço atual (se você recebeu um)',
  'profile.confirmEmail': 'Confirmar a alteração',
  'profile.emailChanged': 'E-mail alterado.',
  'profile.emailWaiting': 'Aguardando o outro endereço. Digite o código dele para concluir.',
  'profile.pendingEmail': 'Uma alteração para {email} aguarda confirmação.',
  'profile.identities': 'Formas de entrar',
  'profile.link': 'Vincular {provider}',
  'profile.unlink': 'Desvincular {provider}',
  'profile.unlinkConfirm': 'Clique de novo para desvincular {provider}',
  'profile.providerEmail': 'E-mail',
  'profile.linked': '{provider} vinculado.',
  'profile.unlinked': '{provider} desvinculado.',
  'profile.password': 'Senha',
  'profile.changePassword': 'Alterar senha',
  'profile.currentPassword': 'Senha atual',
  'profile.newPassword': 'Nova senha',
  'profile.passwordChanged': 'Senha alterada. Os outros dispositivos foram desconectados.',
  'profile.passwordChangedPartial': 'Senha alterada. Não foi possível desconectar os outros dispositivos; faça isso neles.',
  'profile.signOut': 'Sair',
  'profile.signedOutLocalOnly': 'Você saiu neste computador. Não foi possível falar com o servidor para encerrar a sessão lá.',
  'profile.signedOut': 'Você saiu da conta.',
  'profile.license': 'Licença',
  'profile.license.active': 'Ativa',
  'profile.license.trial': 'Teste',
  'profile.license.trialEnds': 'O teste termina em {date}',
  'profile.insecureStore': 'Esta máquina guarda sua sessão em um arquivo comum porque não havia um cofre seguro disponível.',
  'delete.title': 'Excluir conta',
  'delete.lead': 'Isso exclui sua conta e sua licença para sempre. Não pode ser desfeito.',
  'delete.start': 'Excluir minha conta…',
  'delete.confirmWord': 'Digite {word} para confirmar',
  'delete.sendCode': 'Enviar um código de confirmação',
  'delete.codeSent': 'Um código de confirmação foi enviado ao seu e-mail.',
  'delete.code': 'Código de confirmação',
  'delete.confirm': 'Excluir a conta para sempre',
  'delete.done': 'Sua conta foi excluída.',
  'delete.cancel': 'Cancelar',
  'field.required': 'Este campo é obrigatório.',
  'field.email-invalid': 'Isso não parece um endereço de e-mail.',
  'field.code-invalid': 'O código tem {digits} dígitos.',
  'field.password-length': 'A senha deve ter de {min} a {max} caracteres.',
  'field.name-invalid': 'O nome deve ter de 1 a 80 caracteres e não pode começar com hífen.',
  'field.unsafe-text': 'Esse texto tem caracteres que não podem ser usados.',
  'field.show': 'Mostrar',
  'field.hide': 'Ocultar',
  'error.invalid_credentials': 'O e-mail ou a senha não estão corretos.',
  'error.invalid_code': 'Esse código não é válido ou expirou.',
  'error.session_expired': 'Sua sessão terminou. Entre de novo.',
  'error.not_signed_in': 'Você não está conectado.',
  'error.rate_limited': 'Muitas tentativas. Aguarde um instante e tente de novo.',
  'error.unreachable': 'Não foi possível alcançar o servidor da conta. Verifique sua conexão e tente de novo.',
  'error.not_configured': 'Esta versão do app não consegue entrar em uma conta.',
  'error.headless': 'Não há navegador disponível nesta máquina. Entre com um código por e-mail.',
  'error.timeout': 'A entrada demorou demais. Tente de novo.',
  'error.oauth_failed': 'A entrada no navegador não foi concluída. Tente de novo.',
  'error.password_rejected': 'Essa senha não foi aceita.',
  'error.last_identity': 'Esta é sua única forma de entrar, então não pode ser removida. Vincule outra antes.',
  'error.refused': 'Confira os valores e tente de novo.',
  'error.unavailable': 'Não foi possível executar o comando devteam.',
  'error.generic': 'Algo deu errado. Tente de novo.',
};

export type Locale = 'en' | 'pt-BR';

export function localeFrom(language: string | undefined): Locale {
  return (language ?? '').toLowerCase().startsWith('pt') ? 'pt-BR' : 'en';
}

export type Translate = (key: StringKey, vars?: Readonly<Record<string, string>>) => string;

/** Values every message may name, taken from the rules rather than repeated in the text. */
const RULE_VARS: Readonly<Record<string, string>> = {
  digits: String(CODE_LENGTH),
  min: String(PASSWORD_MIN_CHARS),
  max: String(PASSWORD_MAX_CHARS),
};

export function translator(locale: Locale): Translate {
  const table: Readonly<Record<StringKey, string>> = locale === 'pt-BR' ? ptBR : en;
  return (key, vars) => {
    const values = vars === undefined ? RULE_VARS : { ...RULE_VARS, ...vars };
    return table[key].replace(/\{(\w+)\}/g, (match, name: string) => values[name] ?? match);
  };
}

/** The translator for this window's language. Read at call time so a test can set it per case. */
export function currentTranslator(): Translate {
  return translator(localeFrom(typeof navigator === 'undefined' ? undefined : navigator.language));
}

export function currentLocale(): Locale {
  return localeFrom(typeof navigator === 'undefined' ? undefined : navigator.language);
}
