"""Bind, sync and unbind a project against the versioned core (ADR-0007).

A bind is fully reconstructible: the only authoritative files in the project are
``project.json`` and ``user-data/``. Everything else — provider links or copies,
ignore blocks — is regenerated from the store by ``devteam sync``.

Every artifact this module creates is recorded in a per-project manifest, and it
only ever removes paths that manifest claims, or symlinks pointing into the
store. A path it does not recognise is a conflict, never something to overwrite.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from . import plugins as plugins_module
from . import credentials_local, gitignore, hooks, jsonio, paths, prefs, project, providers, quarantine, registry, versions
from .errors import ConflictError, EnvError, UsageError

MODES = ("auto", "link", "copy", "vendored")
MANIFEST_SCHEMA = 1

#: Ignored in the project's own ``.gitignore``: paths every developer on the
#: project needs ignored. ``project.json`` is deliberately absent — it is
#: committed (ADR-0008).
#:
#: The two ``user-data/`` lines are **layout-1 only** and live in their own tuple
#: below, because a layout-2 project has no ``user-data/`` at all: its memory moved
#: into the store, and ``upgrade.RETIRED_GITIGNORE_ENTRIES`` deliberately removes the
#: directory line when it goes. Writing them unconditionally meant the next ``bind``
#: or ``sync`` put back exactly what ``upgrade`` had just retired, so an upgraded
#: project got a dirty ``.gitignore`` on every sync, forever, naming a directory that
#: does not exist. Observed on this repository's own install, right after its upgrade.
PROJECT_GITIGNORE_ENTRIES = (
    ".dev-team-agents/resolved/",
    ".dev-team-agents/VERSION",
    ".dev-team-agents/.worktree-session",
    ".dev-team-agents/.learn-last-run",
    # ADR-0024: the one location of the local credentials file, on both layouts.
    ".dev-team-agents/credentials.local.json",
    ".dev-team-agents/credentials.local.json.*",
    ".worktrees/",
    # `devteam export` defaults to the cache directory, but `--to .` is one keystroke
    # away and the archive can hold credential references and a quarantined
    # pre-upgrade memory directory. Never a thing to commit.
    "devteam-data-*.tar.gz",
)

#: Ignore lines that only make sense while a project's memory is still inside it.
#: `graphify.json`'s negation travels with the directory line: it exists to keep one
#: committed file tracked *inside* `user-data/`, so it is meaningless once there is no
#: `user-data/` — and `upgrade` keeps it out of its retired list for the opposite
#: reason, that a layout-1 project must not lose it.
LEGACY_MEMORY_GITIGNORE_ENTRIES = (
    ".dev-team-agents/user-data/",
    "!.dev-team-agents/user-data/graphify.json",
)


def project_gitignore_entries(project_root):
    """The `.gitignore` entries for this project, given the layout it records."""
    entries = list(PROJECT_GITIGNORE_ENTRIES)
    if project.layout(project_root) == project.LAYOUT_MEMORY_IN_PROJECT:
        entries = list(LEGACY_MEMORY_GITIGNORE_ENTRIES) + entries
    return entries



def manifest_file(project_id):
    # Machine-local (ADR-0013): every artifact path in it is absolute, and two
    # machines binding the same repository produce two different manifests.
    return paths.machine_project_dir(project_id) / "bind-manifest.json"


def read_manifest(project_id):
    return jsonio.read_json(manifest_file(project_id), default=None) or {}


# The implementation moved to `gitignore.local_exclude_file`, because `upgrade` needs it
# too and a second copy of the linked-worktree walk is the kind of duplication that
# diverges. Kept as a module-level alias so the call sites below read unchanged.
_local_exclude_file = gitignore.local_exclude_file


#: Artifact kinds that belong to one machine and must never be in git: a link names
#: an absolute path into this machine's store, a copy is regenerated by every sync,
#: and a pointer, the resolved preferences and a delegated provider tree are
#: projections of machine-local state. An allowlist, not a denylist: a kind added
#: later is exempt until someone decides it is machine-local, rather than silently
#: telling users to untrack a file they own. `settings` is the one kind left out on
#: purpose — `.claude/settings.json` is the project's own file, merged into, and
#: committing it is how a teammate gets the hooks.
MACHINE_LOCAL_KINDS = frozenset({"link", "copy", "pointer", "resolved", "delegated"})


def tracked_artifacts(project_root, manifest):
    """Machine-local bind artifacts that git still tracks, sorted.

    A path in `.git/info/exclude` is ignored only while it is untracked — so a v2
    install, which committed its relative links, keeps them tracked after a bind has
    replaced them with absolute links into this machine's store, and the next commit
    hands every teammate a link to a directory they do not have. Empty in vendored
    mode, where committing the tree is the point, and outside a git repository.

    One `git ls-files` call for every path, not one per artifact: a Claude bind has
    ~160 of them and doctor runs on every session start.
    """
    if manifest.get("mode") == "vendored":
        return []
    candidates = sorted(
        {
            item["path"]
            for item in manifest.get("artifacts", [])
            if item.get("path") and item.get("kind") in MACHINE_LOCAL_KINDS
        }
    )
    if not candidates:
        return []
    try:
        result = subprocess.run(
            ["git", "ls-files", "-z", "--"] + candidates,
            cwd=str(project_root),
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            check=False,
        )
    except OSError:
        return []
    if result.returncode != 0:
        return []
    listed = [p for p in result.stdout.decode("utf-8", "replace").split("\0") if p]
    # `ls-files -- <dir>` lists the files under a tracked directory, not the directory
    # itself, so each listed file is mapped back to the artifact that contains it.
    tracked = set()
    for path in listed:
        for candidate in candidates:
            if path == candidate or path.startswith(candidate + "/"):
                tracked.add(candidate)
                break
    return sorted(tracked)


def symlink_supported(project_root):
    """Probe, rather than guess from the platform name.

    Windows with Developer Mode on supports symlinks; Windows without it does
    not, and neither does a filesystem mounted without the capability. Only an
    attempt answers the question.
    """
    probe_root = Path(project_root) / project.PROJECT_DIR
    # A probe that created the directory removes it again: the bind may still be
    # refused, and a refused bind must leave no `.dev-team-agents/` behind (a pre-v2.1.0
    # install's `migrate-to-root.sh` refuses to move onto one).
    created = not probe_root.exists()
    try:
        probe_root.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(dir=str(probe_root)) as tmp:
            target = Path(tmp) / "target"
            target.mkdir()
            link = Path(tmp) / "link"
            os.symlink(str(target), str(link), target_is_directory=True)
            return link.is_symlink()
    except (OSError, NotImplementedError, AttributeError):
        return False
    finally:
        if created:
            try:
                probe_root.rmdir()  # only ever empty here; never removes content
            except OSError:
                pass


def resolve_mode(requested, project_root):
    """``(mode, reason)`` — reason is set only when ``auto`` had to fall back."""
    if requested not in MODES:
        raise UsageError("unknown mode {!r} (expected one of: {})".format(requested, ", ".join(MODES)))
    if requested == "vendored":
        return "vendored", None
    if requested == "copy":
        return "copy", None
    if requested == "link":
        if not symlink_supported(project_root):
            raise EnvError(
                "this filesystem cannot create symlinks, so --mode=link is impossible",
                hint="Use --mode=copy, or enable Developer Mode on Windows and retry.",
            )
        return "link", None
    if symlink_supported(project_root):
        return "link", None
    return "copy", "symlinks are unavailable here"


def _is_managed_path(rel, path, previous_paths, project_root):
    """True when ``path`` is something dev-team-agents created and may replace.

    Three cases count as managed: a path this project's own manifest claims, a
    symlink into the versioned core (a v3 artifact), and a symlink into the
    project's own ``.dev-team-agents/`` (a **v2** artifact — the relative links
    `install.sh` created). The third is what lets a v2 install be taken over
    without asking the user to delete anything by hand.
    """
    path = Path(path)
    if rel and rel in previous_paths:
        return True
    if not path.is_symlink():
        return False
    try:
        target = Path(os.readlink(str(path)))
    except OSError:
        return False
    if not target.is_absolute():
        target = path.parent / target
    # The pre-v2.1.0 install directory too: `migrate` quarantines that tree and then
    # binds, and the links it committed (`.claude/agents/dev-team ->
    # ../dev-team-agents/agents`, one per skill) are v2 artifacts like any other.
    # `devteam bind` itself never gets here with one — it refuses that shape first.
    roots = [
        paths.core_dir(),
        Path(project_root) / project.PROJECT_DIR,
        Path(project_root) / project.PRE_ROOT_DIR,
    ]
    return any(_is_inside(target, root) for root in roots)


def _is_inside(candidate, root):
    r"""Containment by path components, on both sides fully resolved.

    ``realpath`` on both is what makes this correct on macOS, where ``/var`` is a
    symlink to ``/private/var``: comparing a resolved root against an unresolved
    target would report a path as foreign and refuse to replace an artifact
    dev-team-agents itself created. ``relative_to`` rather than ``startswith``
    compares whole components, so a sibling named ``core-backup`` is not read as
    living inside ``core``.

    ``paths.realpath_normalized`` rather than a bare ``os.path.realpath`` is what
    makes this correct on Windows: ``candidate`` is frequently a symlink target
    read back with ``os.readlink``, which always carries the ``\\?\`` extended
    prefix, while ``root`` is a plain, never-linked-through path that does not
    reliably pick up the same prefix from ``realpath``. Without normalizing both,
    a link this module created its own bind is read back as foreign.
    """
    try:
        resolved_candidate = paths.realpath_normalized(candidate)
        resolved_root = paths.realpath_normalized(root)
        resolved_candidate.relative_to(resolved_root)
        return True
    except (ValueError, OSError):
        return False


def _resolved_location(path):
    """Where ``path`` lives, with its parents resolved but the leaf not followed."""
    path = Path(path)
    try:
        parent = Path(os.path.realpath(str(path.parent)))
    except OSError:
        parent = path.parent
    return parent / path.name


def require_inside(candidate, project_root, what="path"):
    """Refuse to touch anything that resolves outside the project.

    A repository can commit ``.dev-team-agents`` or ``.claude`` as a **symlink**
    — git tracks symlinks natively — and every write below used to follow it,
    because ``mkdir(parents=True)`` and ``rmtree`` traverse links. A clone of a
    hostile or merely careless repo could therefore have its bind land anywhere,
    and a vendored bind could delete a directory in the user's home.

    ``_is_inside`` already compared paths correctly and simply was not called on
    this question. This is that call.
    """
    # Resolve the PARENT, then re-attach the name. Resolving the artifact itself
    # would follow it: a bind artifact is a symlink into the store, so its
    # realpath is legitimately outside the project and every check would refuse
    # the very paths dev-team-agents created. Resolving the parent still catches
    # the case that matters — a symlinked `.claude` or `.dev-team-agents`
    # relocating the write out of the tree.
    # Compared directly rather than through `_is_inside`, which resolves the whole
    # candidate — and resolving a bind artifact follows it into the store.
    located = _resolved_location(candidate)
    try:
        root = Path(os.path.realpath(str(project_root)))
        located.relative_to(root)
        return Path(candidate)
    except (ValueError, OSError):
        pass
    raise ConflictError(
        "{} resolves outside the project: {}".format(what, candidate),
        hint=(
            "A path inside the project (or one of its parents) is a symlink pointing "
            "elsewhere. dev-team-agents will not write or delete through it."
        ),
        details={"path": str(candidate), "project_root": str(project_root)},
    )


def _mkdir_within(directory, project_root):
    """Create ``directory`` one component at a time, never through a symlink."""
    directory = Path(directory)
    require_inside(directory, project_root, what="artifact parent")
    root = Path(project_root).resolve()
    try:
        relative = directory.resolve().relative_to(root)
    except ValueError as exc:  # pragma: no cover - require_inside already checked
        raise ConflictError("cannot create {} outside the project".format(directory)) from exc
    current = root
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            raise ConflictError(
                "{} is a symlink; refusing to create artifacts through it".format(current),
                hint="Remove or repoint that link, then run `devteam sync` again.",
            )
        if not current.exists():
            current.mkdir()
    return current


def _retire_artifact(path, project_id, project_root, group="replaced"):
    """Retire one artifact. Symlinks are unlinked; real content is quarantined.

    A symlink holds no content and ``sync`` recreates it, so unlinking is free.
    A real file or directory is the only copy of whatever is inside it — in
    ``copy`` and ``vendored`` modes that includes anything the user added — so it
    is **moved**, never deleted. Returns ``("unlinked", None)`` or
    ``("quarantined", destination)``.
    """
    path = Path(path)
    require_inside(path, project_root, what="artifact")
    if path.is_symlink():
        path.unlink()
        return "unlinked", None
    destination = quarantine.move(path, project_id, group=group)
    return "quarantined", destination


def _foreign_path_error(dest):
    return ConflictError(
        "{} already exists and was not created by dev-team-agents".format(dest),
        # `bind`, not only `sync`: a first bind lands here too, on a project that has
        # nothing to sync yet.
        hint="Move or remove it, then run `devteam bind` again (or `devteam sync` for a "
        "project that is already bound).",
        details={"path": str(dest)},
    )


#: ``details.reason`` on every refusal whose answer is `devteam migrate` — machine-readable,
#: so a client offers the migration instead of parsing the hint.
V2_INSTALL_REASON = "v2-install"

#: ``details.reason`` on a command that needs a bound project and found no ``project.json``.
NOT_BOUND_REASON = "not-bound"


def _v2_runtime_tree_error(dest, rel):
    return ConflictError(
        "{} is a v2 vendored tree, where this bind links {}".format(dest, rel),
        hint="Run `devteam migrate` — it shows a plan first, binds, and moves the "
        "old tree into a dated quarantine rather than deleting it.",
        details={"path": str(dest), "reason": V2_INSTALL_REASON},
    )


def _v2_copy_error(dest, rel):
    return ConflictError(
        "{} is a copy of a v2 install's {}, where this bind links it".format(dest, rel),
        hint="Run `devteam migrate` — it shows a plan first, binds, and moves the "
        "copy into a dated quarantine rather than deleting it.",
        details={"path": str(dest), "reason": V2_INSTALL_REASON},
    )


#: A Windows checkout without symlink support writes a link as a text file holding
#: its target. Anything larger than this is not one.
_LINK_FILE_MAX = 4096


def _v2_link_file(path):
    """True when ``path`` is a v2 symlink that a checkout wrote as a plain file."""
    try:
        if path.stat().st_size > _LINK_FILE_MAX:
            return False
        text = path.read_text(encoding="utf-8").strip()
    except (OSError, UnicodeDecodeError):
        return False
    if not text or "\n" in text:
        return False
    # `.dev-team-agents/` for a root install, `.claude/dev-team-agents/` before v2.1.0.
    parts = Path(text.replace("\\", "/")).parts
    return project.PROJECT_DIR in parts or Path(project.PRE_ROOT_DIR).name in parts


def _frontmatter_name(skill_file):
    try:
        with open(str(skill_file), encoding="utf-8") as stream:
            if stream.readline().strip() != "---":
                return None
            for _ in range(50):
                line = stream.readline()
                if not line or line.strip() == "---":
                    return None
                key, _, value = line.partition(":")
                if key.strip() == "name":
                    return value.strip().strip("\"'")
    except (OSError, UnicodeDecodeError):
        return None
    return None


def v2_copy(rel, dest, version_dir):
    """True when ``dest`` is a v2 install's ``rel`` link, materialized as real content.

    v2 committed relative links (`.claude/agents/dev-team -> ../../.dev-team-agents/
    agents`, one per skill). A tool that copies a project dereferencing links, or a
    checkout without symlink support, turns them into real directories or text files,
    which `_is_managed_path` cannot vouch for. Only content that is recognisably the
    framework's counts — the agents or commands directory holding nothing but `.md`
    files, at least one named like the framework's own; a skill whose frontmatter
    `name` is the framework skill's — so a project's own directory at the same path is
    still refused as foreign.
    """
    dest = Path(dest)
    if dest.is_symlink() or not dest.exists():
        return False
    if dest.is_file():
        return _v2_link_file(dest)
    parts = Path(rel).parts
    if len(parts) != 3 or parts[0] != ".claude":
        return False
    if parts[1] in ("agents", "commands"):
        known = {item.name for item in (Path(version_dir) / parts[1]).glob("*.md")}
        entries = list(dest.iterdir())
        return (
            bool(entries)
            and all(
                item.is_file() and not item.is_symlink() and item.suffix == ".md" for item in entries
            )
            and any(item.name in known for item in entries)
        )
    if parts[1] == "skills":
        return _frontmatter_name(dest / "SKILL.md") == parts[2]
    return False


def v2_copies(version_dir, project_root):
    """Every Claude artifact path holding a materialized v2 copy, project-relative."""
    root = Path(project_root)
    return [
        rel_path.as_posix()
        for rel_path, _source in providers.claude_artifacts(version_dir)
        if v2_copy(rel_path.as_posix(), root / rel_path, version_dir)
    ]


def _preflight(
    version_dir,
    project_root,
    mode,
    selected,
    previous_paths,
    previous_copies,
    previous_artifacts=(),
    vacated=frozenset(),
):
    """Refuse a bind that would collide, before anything is written.

    The same conditions `_materialize`, `_runtime_root` and the delegated installers
    refuse on, checked for every destination of every selected provider up front.
    Found in the middle of the bind, a collision left `project.json` behind on a
    project that was never bound — and a pre-v2.1.0 install's own
    `migrate-to-root.sh` then refused to run, because `.dev-team-agents/` existed.

    Every mode, vendored included: vendored re-vendors (quarantines) only its own
    trees under `.dev-team-agents/`. A provider path outside them that the project
    owns is refused there exactly as in link mode — moving a project's own agent out
    of the way to install one of the same name silently changes which agent runs.

    Returns ``{provider: targets}`` for the delegated providers, and the subset of
    those targets that already exist and are framework-owned, which the installer is
    told to trust. Both are computed once here and reused by the bind.
    """
    delegated = {}
    owned = {}
    root = Path(project_root)
    # Vendored links the Claude tree whatever the selection (`_vendored_tree`).
    if "claude" in selected or mode == "vendored":
        for rel_path, _source in providers.claude_artifacts(version_dir):
            rel = rel_path.as_posix()
            dest = root / rel_path
            if rel in vacated or not (dest.exists() or dest.is_symlink()):
                continue
            if _is_managed_path(rel, dest, previous_paths, project_root):
                continue
            if v2_copy(rel, dest, version_dir):
                raise _v2_copy_error(dest, rel)
            raise _foreign_path_error(dest)
    # Vendored mode puts real trees at these paths on purpose; it has no runtime links.
    for name in RUNTIME_TREES if mode != "vendored" else ():
        rel = (Path(project.PROJECT_DIR) / name).as_posix()
        dest = root / rel
        if rel in vacated:
            continue
        if dest.is_dir() and not dest.is_symlink() and rel not in previous_copies:
            raise _v2_runtime_tree_error(dest, rel)
        if name == "plugins" and not (Path(version_dir) / name).exists():
            continue  # `_runtime_root` skips it too
        if (dest.exists() or dest.is_symlink()) and not _is_managed_path(rel, dest, previous_paths, project_root):
            raise _foreign_path_error(dest)
    for provider_name in selected:
        if provider_name not in providers.DELEGATED_INSTALLERS:
            continue
        targets = providers.delegated_targets(provider_name, version_dir, project_root)
        claimed = set(previous_paths) | set(providers.legacy_owned(previous_artifacts, targets))
        existing = []
        for rel in targets:
            dest = root / rel
            if not (dest.exists() or dest.is_symlink()):
                continue
            if not _is_managed_path(rel, dest, claimed, project_root):
                raise _foreign_path_error(dest)
            existing.append(rel)
        delegated[provider_name] = targets
        owned[provider_name] = existing
    return delegated, owned


def _materialize(source, dest, mode, previous_paths, rel, project_root, project_id, retired):
    """Create one artifact, returning ``link`` or ``copy``.

    ``retired`` collects anything moved to quarantine, so a caller can report it.
    """
    source = Path(source)
    dest = Path(dest)
    if not source.exists():
        raise EnvError("core is missing {}".format(source))

    require_inside(dest, project_root, what="artifact")

    if dest.exists() or dest.is_symlink():
        if not _is_managed_path(rel, dest, previous_paths, project_root):
            raise _foreign_path_error(dest)
        action, destination = _retire_artifact(dest, project_id, project_root)
        if action == "quarantined":
            retired.append({"path": rel, "to": str(destination)})

    _mkdir_within(dest.parent, project_root)
    try:
        if mode == "link":
            os.symlink(str(source), str(dest), target_is_directory=source.is_dir())
            return "link"
        if source.is_dir():
            shutil.copytree(str(source), str(dest), symlinks=False)
        else:
            shutil.copy2(str(source), str(dest))
    except OSError as exc:
        raise EnvError(
            "cannot create {}: {}".format(dest, exc),
            hint="Check permissions on the project directory.",
        ) from exc
    return "copy"


def _vendored_tree(version_dir, project_root, previous_paths, project_id, retired):
    """v2 layout: the framework inside the project, with relative links.

    Every existing framework tree under `.dev-team-agents/` is **quarantined**, never
    deleted, and re-vendored. A Claude artifact path is replaced only when
    `_preflight` found it framework-owned; a project-owned one refused the bind before
    this ran. The previous code had
    a delete branch justified as "a v2 install being re-vendored is the
    documented update" — which is exactly the judgment call the No-Destruction
    Rule says not to make: a hand-written agent sitting in that directory is
    indistinguishable from a framework file, and it was destroyed.
    """
    install_dir = Path(project_root) / project.PROJECT_DIR
    require_inside(install_dir, project_root, what="install directory")
    created = []
    for name in versions.CORE_TREES:
        source = Path(version_dir) / name
        if not source.is_dir():
            continue
        dest = install_dir / name
        # `.as_posix()`, not `str()`: this path is stored in the manifest, the
        # local exclude block and `.gitignore` — all of which are read back by
        # `_is_managed_path`/`unbind`/`doctor` as plain strings, or interpreted by
        # git, which only understands forward slashes in an ignore pattern. A
        # native-separator string here matched nothing on Windows: bind's own
        # artifacts went un-ignored and every manifest lookup keyed on this
        # string missed.
        rel = Path(project.PROJECT_DIR, name).as_posix()
        if dest.exists() or dest.is_symlink():
            action, destination = _retire_artifact(
                dest, project_id, project_root, group="revendored"
            )
            if action == "quarantined":
                retired.append({"path": rel, "to": str(destination)})
        _mkdir_within(dest.parent, project_root)
        shutil.copytree(str(source), str(dest), symlinks=False)
        created.append({"path": rel, "kind": "copy"})

    for rel_path, source in providers.claude_artifacts(install_dir):
        dest = Path(project_root) / rel_path
        rel = rel_path.as_posix()
        require_inside(dest, project_root, what="artifact")
        if dest.exists() or dest.is_symlink():
            action, destination = _retire_artifact(dest, project_id, project_root)
            if action == "quarantined":
                retired.append({"path": rel, "to": str(destination)})
        _mkdir_within(dest.parent, project_root)
        depth = len(rel_path.parts) - 1
        relative_target = Path(*([".."] * depth)) / source.relative_to(Path(project_root))
        # `.as_posix()`: this string is the symlink's on-disk target, not merely a
        # value this process reads back. A backslash target resolves fine on the
        # Windows checkout that created it, but the whole point of a *relative*
        # vendored link is that a POSIX clone of the same repository can follow
        # it too — and a POSIX symlink reader has no notion of `\` as a separator.
        os.symlink(relative_target.as_posix(), str(dest), target_is_directory=True)
        created.append({"path": rel, "kind": "relative-link"})
    return created


def _stamp_installed_version(project_root, project_id, version):
    """Record the resolved version where the v2 readers already look.

    `/devteam:version`, the session banner and telemetry all read
    `installed_version` from `state.json`, and no v3 path wrote it — so a migrated
    project reported its v2 number forever. Retiring the key and repointing those
    four readers is a later decision; stamping it is what makes them truthful now.
    """
    state_file = project.state_dir(project_root, project_id) / "state.json"
    state = jsonio.read_json(state_file, default=None)
    if state is None:
        state = {}
    if not isinstance(state, dict):
        return None
    if state.get("installed_version") == version:
        return state_file
    state["installed_version"] = version
    jsonio.write_json_atomic(state_file, state)
    return state_file


def _other_checkouts_bound(project_id, project_root):
    """True when another live checkout of the same repository is still bound."""
    entry = registry.get(project_id) or {}
    candidates = [entry.get("path")] + list(entry.get("worktrees", []))
    target = str(Path(project_root).resolve())
    for candidate in candidates:
        if not candidate or candidate == target:
            continue
        if Path(candidate).is_dir():
            return True
    return False


def _git_common_dir(path):
    """The shared git directory for ``path``, or ``None`` outside a repository."""
    return project.git_common_dir(path)


def _same_git_repository(path_a, path_b):
    """True when both paths are checkouts of one repository (a linked worktree).

    A worktree of a bound repository carries the **committed** ``project.json``,
    so it presents the same ``project_id`` at a second path — which is exactly the
    shape of the fork collision. Telling the two apart matters because this
    repository's own CLAUDE.md mandates worktrees: treating one as a fork told the
    user to reassign an identity in a tracked file on a feature branch, which on
    merge would rename the main checkout's identity and orphan its memory.
    """
    common_a = _git_common_dir(path_a)
    common_b = _git_common_dir(path_b)
    return common_a is not None and common_a == common_b


#: The version trees the framework's own text reaches by a project-relative path:
#: 121 references to `.dev-team-agents/scripts/…` (hooks, `new-adr.sh`,
#: `graphify-refresh.sh`, the reuse and design-token lints), 17 to
#: `.dev-team-agents/templates/…`, and the plugin manifests and hook scripts under
#: `.dev-team-agents/plugins/…` (ADR-0019; the per-project *settings* live beside it in
#: `plugin-settings/`, never inside this link). Nothing shipped reads agents, commands or
#: skills through `.dev-team-agents/` — Claude Code finds those under `.claude/`.
#: A core version without one of these trees (`plugins/` before ADR-0019) is skipped
#: rather than refused, so an older pinned version still binds.
RUNTIME_TREES = ("scripts", "templates", "plugins")


def _runtime_root(version_dir, project_root, mode, previous_paths, previous_copies, project_id, retired):
    """Link the two trees the framework's text names, exactly where it names them.

    This used to be one `core` pointer to the whole version, on the claim that it
    resolved every project-relative reference. It resolved none of them: the text says
    `.dev-team-agents/scripts/new-adr.sh`, the pointer made
    `.dev-team-agents/core/scripts/new-adr.sh`, and the reuse and design-token Stop
    gates — which look for `.dev-team-agents/scripts/<lint>.sh` and exit 0 when it is
    absent — were silently off in every v3 project. Linking each tree at the path
    the text already uses fixes all of them without rewriting a reference, and makes
    `settings.json`'s hook path the same one a v2 install used.

    A real directory at one of these paths is a v2 vendored tree unless the previous
    manifest records a `copy` there — the path alone is not enough: a link-mode bind
    lists the same path for its link, and trusting that would quarantine a real tree
    the bind never made. Replacing it would run the hooks from nothing and linking
    beside it is impossible, so it is refused with the one command that handles it.
    """
    created = []
    for name in RUNTIME_TREES:
        rel_path = Path(project.PROJECT_DIR) / name
        # `.as_posix()`: see the comment on the same pattern in `_vendored_tree` —
        # this string ends up in the manifest, the exclude block and `.gitignore`.
        rel = rel_path.as_posix()
        dest = Path(project_root) / rel_path
        if dest.is_dir() and not dest.is_symlink() and rel not in previous_copies:
            raise _v2_runtime_tree_error(dest, rel)
        if not (Path(version_dir) / name).exists() and name == "plugins":
            # A core version older than ADR-0019 has no plugins tree; refusing the whole
            # bind for that would strand a project pinned to it.
            continue
        kind = _materialize(
            Path(version_dir) / name,
            dest,
            "link" if mode != "copy" else "copy",
            previous_paths,
            rel,
            project_root,
            project_id,
            retired,
        )
        created.append({"path": rel, "kind": kind})
    return created


def _prepare(root, provider_names, mode, pin, emitter, vacated=frozenset()):
    """Every check that can refuse a bind, run before its first write.

    ``vacated`` names project-relative paths the caller moves away before binding —
    `migrate` quarantines the v2 install first, and checks the bind with this before
    it moves anything, so a refused bind can no longer leave a half-migrated project.
    """
    project_root = project.resolve_root(root)
    if not project_root.is_dir():
        raise UsageError("not a directory: {}".format(project_root))

    requested = list(provider_names) if provider_names else providers.detect(project_root)
    unknown = [p for p in requested if p not in providers.ALL_PROVIDERS]
    if unknown:
        raise UsageError(
            "unknown provider(s): {} (expected: {})".format(
                ", ".join(unknown), ", ".join(providers.ALL_PROVIDERS)
            )
        )
    selected = [p for p in providers.ALL_PROVIDERS if p in set(requested)]

    # Everything that can refuse the bind runs BEFORE the first write. A missing
    # `jq` used to surface from inside the opencode installer, after 154 Claude
    # symlinks already existed and before the manifest, registry entry or exclude
    # block recorded them — leaving artifacts nothing could clean up and nothing
    # kept out of git.
    for provider_name in selected:
        providers.require_tools(provider_name)

    resolved_mode, fallback_reason = resolve_mode(mode, project_root)
    if fallback_reason and emitter:
        emitter.warn("mode=copy: {}".format(fallback_reason))

    # The identity is READ here and written only after the preflight below: a first
    # bind that collides must leave the project exactly as it found it. `known_id` is
    # None for a project never bound, which has no registry entry and no manifest.
    identity = project.load(project_root)
    known_id = registry.registered_id(project_root, identity)

    # `pin=None` means "leave the pin alone", not "clear it". Reading the stored
    # pin here is what stops a bare `devteam bind` from silently moving a pinned
    # project to `current` — the spec calls bind idempotent, and it is the one
    # command a user re-runs casually.
    existing = registry.get(known_id) if known_id is not None else None
    effective_pin = pin if pin is not None else (existing or {}).get("pin")

    # The registry collision check must also precede the writes, so a refused
    # bind (a fork inheriting an identity) leaves nothing behind.
    is_worktree_of_bound = False
    if existing and existing.get("path") != str(project_root.resolve()):
        other = Path(existing["path"])
        if other.exists():
            if _same_git_repository(other, project_root):
                # A linked worktree of an already-bound repository. It carries the
                # same committed project_id, which used to be read as a fork
                # collision — and following that advice would have written a new
                # identity into a tracked file on a feature branch, renaming the
                # main checkout's identity on merge.
                is_worktree_of_bound = True
            else:
                raise ConflictError(
                    "project_id {} is already bound to {}".format(known_id, other),
                    hint=(
                        "Two checkouts share one identity. Run `devteam doctor "
                        "--reassign-identity` in the copy that should get a new one."
                    ),
                    details={"project_id": known_id, "bound_path": str(other)},
                )

    version = versions.resolve(effective_pin)
    version_dir = versions.require(version)

    previous = read_manifest(known_id) if known_id is not None else {}
    previous_paths = {item.get("path") for item in previous.get("artifacts", [])}
    previous_copies = {
        item.get("path") for item in previous.get("artifacts", []) if item.get("kind") == "copy"
    }
    delegated_targets, delegated_owned = _preflight(
        version_dir,
        project_root,
        resolved_mode,
        selected,
        previous_paths,
        previous_copies,
        previous.get("artifacts", []),
        vacated=vacated,
    )

    return {
        "project_root": project_root,
        "fallback_reason": fallback_reason,
        "selected": selected,
        "resolved_mode": resolved_mode,
        "known_id": known_id,
        "effective_pin": effective_pin,
        "is_worktree_of_bound": is_worktree_of_bound,
        "version": version,
        "version_dir": version_dir,
        "previous": previous,
        "previous_paths": previous_paths,
        "previous_copies": previous_copies,
        "delegated_targets": delegated_targets,
        "delegated_owned": delegated_owned,
    }


def check(root=None, provider_names=None, mode="auto", pin=None, vacated=frozenset()):
    """Raise what :func:`bind` would refuse with, writing nothing."""
    _prepare(root, provider_names, mode, pin, None, vacated=frozenset(vacated))


def bind(root=None, provider_names=None, mode="auto", pin=None, emitter=None):
    """Bind ``root`` to the store. Idempotent, and safe to re-run."""
    ready = _prepare(root, provider_names, mode, pin, emitter)
    project_root = ready["project_root"]
    selected = ready["selected"]
    resolved_mode = ready["resolved_mode"]
    fallback_reason = ready["fallback_reason"]
    known_id = ready["known_id"]
    effective_pin = ready["effective_pin"]
    is_worktree_of_bound = ready["is_worktree_of_bound"]
    version = ready["version"]
    version_dir = ready["version_dir"]
    previous = ready["previous"]
    previous_paths = ready["previous_paths"]
    previous_copies = ready["previous_copies"]
    delegated_targets = ready["delegated_targets"]
    delegated_owned = ready["delegated_owned"]

    # The first write.
    data, created_identity = project.ensure(project_root, project_id=known_id)
    project_id = data["project_id"]

    artifacts = []
    retired = []
    merged = []
    if resolved_mode == "vendored":
        artifacts.extend(
            _vendored_tree(version_dir, project_root, previous_paths, project_id, retired)
        )
    elif "claude" in selected:
        for rel_path, source in providers.claude_artifacts(version_dir):
            # `.as_posix()`: see the comment on the same pattern in `_vendored_tree`.
            rel = rel_path.as_posix()
            kind = _materialize(
                source,
                Path(project_root) / rel_path,
                resolved_mode,
                previous_paths,
                rel,
                project_root,
                project_id,
                retired,
            )
            artifacts.append({"path": rel, "kind": kind})

    # Every provider, not only Claude: the Codex hooks.json and the opencode plugin
    # call `.dev-team-agents/scripts/hooks/…` too. Not in vendored mode, where the
    # real trees are already at these paths.
    if resolved_mode != "vendored":
        artifacts.extend(
            _runtime_root(
                version_dir,
                project_root,
                resolved_mode,
                previous_paths,
                previous_copies,
                project_id,
                retired,
            )
        )
    if "claude" in selected or resolved_mode == "vendored":
        artifacts.extend(hooks.wire(project_root, emitter=emitter))

    # Resolved preferences and the state pointer are written on every bind and
    # every sync: both are projections of state that lives elsewhere, so a stale
    # one is a bug rather than a user edit to preserve.
    # Before the projection, so it already carries what a v2 preferences file held.
    preferences_import = prefs.import_legacy(project_root, project_id, version, emitter=emitter)
    artifacts.append(prefs.materialize(project_root, project_id, version))
    # Pre-plugin `user-data/graphify.json` -> `plugin-settings/graphify.json`. Idempotent,
    # and a no-op when the new file already exists (the leftover is reported, not touched).
    plugins_migration = plugins_module.migrate_legacy(project_root)
    for leftover in plugins_migration["skipped"]:
        if emitter:
            emitter.warn("plugin {}: {}".format(leftover["plugin"], leftover["reason"]))
    artifacts.extend(project.write_pointers(project_root, project_id))
    _stamp_installed_version(project_root, project_id, version)

    if project.upgrade_available(project_root) and emitter is not None:
        emitter.warn(
            "this project still keeps its memory in {}/{} — run `devteam upgrade` to move it "
            "into the store and leave the project clean".format(
                project.PROJECT_DIR, project.LEGACY_MEMORY_DIR
            )
        )

    # Every mode. In vendored mode the installers find the vendored `skills/` and link
    # it relatively, and the hook paths they write point into the vendored `scripts/`,
    # so everything they produce is portable and committed with the rest of the tree.
    if "opencode" in selected:
        providers.install_opencode(
            version_dir, project_root, owned=delegated_owned.get("opencode")
        )
        artifacts.extend(
            providers.delegated_artifacts(
                "opencode", project_root, delegated_targets.get("opencode", [])
            )
        )
        merged.extend(providers.merged_project_files("opencode", project_root))
    if "codex" in selected:
        providers.install_codex(version_dir, project_root, owned=delegated_owned.get("codex"))
        artifacts.extend(
            providers.delegated_artifacts(
                "codex", project_root, delegated_targets.get("codex", [])
            )
        )
        merged.extend(providers.merged_project_files("codex", project_root))

    stale = _prune_stale(
        project_root, previous, {item["path"] for item in artifacts}, project_id, version_dir
    )

    manifest = {
        "schema": MANIFEST_SCHEMA,
        "project_id": project_id,
        "path": str(project_root),
        "version": version,
        "mode": resolved_mode,
        "providers": selected,
        "artifacts": artifacts,
    }
    jsonio.write_json_atomic(manifest_file(project_id), manifest)

    if is_worktree_of_bound:
        registry.add_worktree(project_id, project_root, version)
    else:
        registry.upsert(
            project_id,
            project_root,
            selected,
            resolved_mode,
            pin=effective_pin,
            extra={"last_synced_version": version},
        )

    ignore_changed, ignore_action = gitignore.apply_managed_block(
        Path(project_root) / ".gitignore", project_gitignore_entries(project_root)
    )

    exclude_action = "skipped"
    exclude_file = _local_exclude_file(project_root)
    if exclude_file is not None and resolved_mode != "vendored":
        # Machine-local kinds only — the same allowlist `tracked_artifacts` reports
        # on, so "what bind hides from git" and "what doctor says must not be in git"
        # are one rule. Every path used to go in, `.claude/settings.json` included:
        # on a project that had not committed it yet, `git add -A` skipped the file
        # the hooks live in, and no teammate ever received them.
        entries = sorted(
            {item["path"] for item in artifacts if item.get("kind") in MACHINE_LOCAL_KINDS}
        )
        _, exclude_action = gitignore.apply_managed_block(exclude_file, entries)
    elif exclude_file is None and emitter:
        emitter.warn(
            "not a git repository: bind artifacts were not added to any ignore file"
        )

    return {
        "project_id": project_id,
        "path": str(project_root),
        "version": version,
        "mode": resolved_mode,
        "providers": selected,
        "artifacts": len(artifacts),
        "retired": retired,
        "merged_project_files": sorted(set(merged)),
        "pin": effective_pin,
        "identity_created": created_identity,
        "pruned": stale,
        "gitignore": ignore_action if ignore_changed else "unchanged",
        "git_exclude": exclude_action,
        "fallback_reason": fallback_reason,
        "preferences_import": preferences_import,
    }


def _expand_legacy_delegated(item, version_dir, project_root):
    """The framework-owned paths hidden behind an old directory-level record.

    Never the directory itself — it may hold the project's own agents and skills.
    Only the targets the installer writes, under that directory. Without a core
    version to ask, nothing: leaving a framework file behind is recoverable,
    moving a project file is not what the user asked for.
    """
    if version_dir is None or item.get("provider") not in providers.DELEGATED_INSTALLERS:
        return []
    try:
        targets = providers.delegated_targets(item["provider"], version_dir, project_root)
    except (EnvError, ConflictError):
        return []
    base = item["path"]
    return [rel for rel in targets if rel.startswith(base + "/")]


def _stale_candidates(previous_artifacts, current_paths, version_dir, project_root):
    """``(rel, kind)`` pairs a previous manifest claims that the current bind does not.

    An old directory-level delegated record is expanded to the files under it that
    the installer owns (see :func:`_expand_legacy_delegated`); an old record of the
    Codex hooks file is treated as the merged file it is.
    """
    out = []
    for item in previous_artifacts:
        rel = item.get("path")
        if not rel or rel in current_paths:
            continue
        if providers.is_legacy_delegated(item):
            if rel == providers.CODEX_HOOKS_FILE:
                out.append((rel, "codex-hooks"))
                continue
            for child in _expand_legacy_delegated(item, version_dir, project_root):
                if child not in current_paths:
                    out.append((child, "delegated"))
            continue
        out.append((rel, item.get("kind")))
    return out


def _prune_stale(project_root, previous, current_paths, project_id, version_dir=None):
    """Retire artifacts a previous bind made that this one no longer needs."""
    unlinked = []
    quarantined = []
    for rel, kind in _stale_candidates(
        previous.get("artifacts", []), current_paths, version_dir, project_root
    ):
        if kind == "codex-hooks":
            try:
                events = providers.unwire_codex_hooks(project_root)
            except OSError:
                continue
            if events:
                unlinked.append("{} (hooks: {})".format(rel, ", ".join(events)))
            continue
        candidate = Path(project_root) / rel
        if not (candidate.exists() or candidate.is_symlink()):
            continue
        try:
            action, destination = _retire_artifact(
                candidate, project_id, project_root, group="pruned"
            )
        except (OSError, ConflictError):
            continue
        if action == "unlinked":
            unlinked.append(rel)
        elif destination is not None:
            quarantined.append({"path": rel, "to": str(destination)})
    return {"unlinked": unlinked, "quarantined": quarantined}


def sync_project(project_id, emitter=None):
    entry = registry.get(project_id)
    if entry is None:
        raise EnvError("project {} is not bound".format(project_id))
    root = Path(entry["path"])
    if not root.is_dir():
        raise EnvError(
            "bound path no longer exists: {}".format(root),
            hint="Run `devteam doctor` from the project's new location to reconcile it.",
        )
    result = bind(
        root,
        provider_names=entry.get("providers"),
        mode=entry.get("mode", "auto"),
        pin=entry.get("pin"),
        emitter=emitter,
    )
    # Linked worktrees of the same repository carry their own artifacts and are
    # refreshed alongside the checkout that owns the registry entry.
    refreshed = []
    for worktree in entry.get("worktrees", []):
        if not Path(worktree).is_dir():
            continue
        bind(
            worktree,
            provider_names=entry.get("providers"),
            mode=entry.get("mode", "auto"),
            pin=entry.get("pin"),
            emitter=emitter,
        )
        refreshed.append(worktree)
    result["worktrees"] = refreshed
    result["credentials_local"] = credentials_local.relocate_safely(root, project_id)
    registry.touch_sync(project_id, result["version"])
    return result


def sync_all(emitter=None):
    results = []
    problems = []
    for project_id in sorted(registry.entries()):
        try:
            results.append(sync_project(project_id, emitter=emitter))
        except (EnvError, ConflictError) as exc:
            problems.append({"project_id": project_id, "error": exc.message})
            if emitter:
                emitter.warn("{}: {}".format(project_id, exc.message))
        except OSError as exc:
            # A read-only mount, an unmounted volume or a permission change is the
            # likeliest failure across many projects. Escaping as a traceback
            # aborted every project after this one and emitted zero bytes on
            # stdout, breaking the --json contract.
            message = "{}: {}".format(type(exc).__name__, exc)
            problems.append({"project_id": project_id, "error": message})
            if emitter:
                emitter.warn("{}: {}".format(project_id, message))
    return {"synced": results, "problems": problems}


def _prune_empty_dirs(project_root, relpaths):
    """Remove directories an unbind emptied, deepest first.

    `rmdir` is the whole safety argument: it refuses a directory that still has
    anything in it, so a user's own file in `.claude/` keeps its parent alive without
    this function needing to know about it. Bounded to paths inside the project, and
    never the project root.

    Without this, an unbind left `.claude/agents`, `.claude/commands`, `.claude/skills`
    and `.dev-team-agents/resolved` behind as empty directories — nothing broken, but
    four directories the project did not have before the bind and does not need after it.
    """
    root = Path(project_root).resolve()
    candidates = set()
    for rel in relpaths:
        # `rel` may carry a note appended for the report, e.g. the settings entry.
        rel = str(rel).split(" (", 1)[0]
        if not rel or Path(rel).is_absolute() or ".." in Path(rel).parts:
            continue
        current = (root / rel).parent
        while True:
            try:
                resolved = current.resolve()
            except OSError:
                break
            if resolved == root or root not in resolved.parents:
                break
            candidates.add(resolved)
            current = current.parent
    removed = []
    # Deepest first, so a parent becomes empty before it is tried.
    for directory in sorted(candidates, key=lambda d: len(d.parts), reverse=True):
        try:
            directory.rmdir()
        except OSError:
            continue
        # `.as_posix()`: `removed_dirs` is reported to the caller (and to the
        # `--json` contract) alongside every other artifact path in this module,
        # all of which are forward-slash. A native-separator entry here was the
        # one inconsistent value in that list on Windows.
        removed.append(directory.relative_to(root).as_posix())
    return sorted(removed)


def unbind(root=None, project_id=None, keep_artifacts=False):
    """Remove bind artifacts and the registry entry.

    ``project.json`` and everything under ``user-data/`` stay: identity and
    memory are never collateral damage of an unbind. Real directories — which in
    ``copy`` and ``vendored`` modes may contain files the user added — are moved
    to quarantine rather than deleted.
    """
    if project_id is None:
        project_root = project.resolve_root(root)
        data = project.load(project_root)
        if data is None:
            raise UsageError("{} is not a bound project".format(project_root))
        project_id = data["project_id"]
    else:
        entry = registry.get(project_id)
        if entry is None:
            raise EnvError("project {} is not bound".format(project_id))
        bound_path = entry.get("path")
        if not bound_path:
            raise EnvError(
                "registry entry for {} has no path".format(project_id),
                hint="Remove the entry by hand, or re-bind the project.",
            )
        project_root = Path(bound_path)

    manifest = read_manifest(project_id)
    unlinked = []
    quarantined = []
    problems = []
    kept_pointers = []
    # A layout-2 project's memory lives in the store, and the two pointers are the only
    # record of where. Removing them leaves `project.json` still saying `layout: 2` while
    # nothing can resolve the store paths — and the resolvers then fall back to the
    # in-project layout-1 path, so the next writer creates a fresh, empty
    # `.dev-team-agents/user-data/state.json` beside a store copy holding the real state.
    # Observed on this repository's own unbind, not derived from reading the code.
    keep_pointers = project.layout(project_root) >= project.CURRENT_LAYOUT
    if not keep_artifacts:
        legacy_version_dir = None
        if any(providers.is_legacy_delegated(item) for item in manifest.get("artifacts", [])):
            try:
                legacy_version_dir = versions.require(manifest.get("version"))
            except (EnvError, UsageError, TypeError):
                legacy_version_dir = None
        items = []
        for item in manifest.get("artifacts", []):
            if not providers.is_legacy_delegated(item):
                items.append(item)
            elif item.get("path") == providers.CODEX_HOOKS_FILE:
                items.append(dict(item, kind="codex-hooks"))
            else:
                items.extend(
                    {"path": child, "kind": "delegated", "provider": item.get("provider")}
                    for child in _expand_legacy_delegated(item, legacy_version_dir, project_root)
                )
        for item in items:
            rel = item.get("path")
            # An entry with no path used to become `Path(project_root) / ""`,
            # which IS the project root — and the removal helper then deleted the
            # whole project, source code included, before crashing on the missing
            # key. `_prune_stale` already guarded this; unbind did not.
            if not rel or Path(rel).is_absolute() or ".." in Path(rel).parts:
                problems.append({"path": rel, "error": "not a relative artifact path"})
                continue
            if item.get("kind") == "pointer" and keep_pointers:
                # Kept, not unlinked. `pointer` used to be lumped in with `resolved`
                # below, on the reasoning that both are generated projections carrying no
                # state of their own. That is true of `resolved` — the preference cascade
                # regenerates it — and false of a pointer once the memory it names is
                # outside the project: nothing regenerates it after an unbind, and its
                # absence is worse than staleness, because the fallback writes *into* the
                # project. Same category as `project.json`: a record of where this
                # project's own data is, not an artifact of being bound.
                kept_pointers.append(rel)
                continue
            if item.get("kind") in ("resolved", "pointer"):
                # Generated projections: unlink and move on. They carry no state
                # of their own — the layers they project from are untouched.
                candidate = Path(project_root) / rel
                if candidate.exists():
                    try:
                        candidate.unlink()
                        unlinked.append(rel)
                    except OSError as exc:
                        problems.append({"path": rel, "error": str(exc)})
                continue
            if item.get("kind") == "codex-hooks":
                # Merged into, like `.claude/settings.json`: only our entries go.
                try:
                    events = providers.unwire_codex_hooks(project_root)
                except OSError as exc:
                    problems.append({"path": rel, "error": str(exc)})
                else:
                    if events:
                        unlinked.append("{} (hooks: {})".format(rel, ", ".join(events)))
                continue
            if item.get("kind") == "settings":
                # `.claude/settings.json` belongs to the project and may be
                # committed. Remove only the hook entries we registered.
                try:
                    events = hooks.unwire(project_root)
                except (OSError, EnvError) as exc:
                    problems.append({"path": rel, "error": str(exc)})
                else:
                    if events:
                        unlinked.append("{} (hooks: {})".format(rel, ", ".join(events)))
                continue
            candidate = Path(project_root) / rel
            if not (candidate.exists() or candidate.is_symlink()):
                continue
            try:
                action, destination = _retire_artifact(
                    candidate, project_id, project_root, group="unbound"
                )
            except (OSError, ConflictError) as exc:
                problems.append({"path": rel, "error": str(exc)})
                continue
            if action == "unlinked":
                unlinked.append(rel)
            elif destination is not None:
                quarantined.append({"path": rel, "to": str(destination)})
        exclude_file = _local_exclude_file(project_root)
        if exclude_file is not None and not _other_checkouts_bound(project_id, project_root):
            # git reads only $GIT_COMMON_DIR/info/exclude for a linked worktree —
            # verified, the per-worktree file is ignored — so the block is shared
            # by every checkout of the repository. Clearing it while another
            # worktree is still bound would un-ignore that worktree's artifacts.
            # Cleared, except for anything unbind kept: an entry it leaves behind still
            # needs ignoring, or the unbind trades two untracked files for a clean block.
            gitignore.apply_managed_block(exclude_file, sorted(kept_pointers))

    pruned_dirs = []
    if not keep_artifacts:
        pruned_dirs = _prune_empty_dirs(
            project_root,
            [item["path"] for item in quarantined] + list(unlinked),
        )

    registry.remove(project_id)
    return {
        "project_id": project_id,
        "removed_dirs": pruned_dirs,
        "path": str(project_root),
        "unlinked": unlinked,
        "quarantined": quarantined,
        "problems": problems,
        "kept": ["project.json", "user-data/"] + sorted(kept_pointers),
    }