"""Managed ignore blocks.

Bind artifacts point at an absolute path inside one developer's store, so they
can never be committed (ADR-0007). Two files carry the ignores, for two
different audiences:

* ``.gitignore`` — the handful of project-level paths every developer on the
  project needs ignored. Committed, reviewable, short.
* ``.git/info/exclude`` — the per-provider artifacts, including one entry per
  linked skill. Local to the clone, which is exactly what a per-developer bind
  is, and keeps 150+ generated lines out of a shared file.

Both are edited only between markers; everything outside them is preserved byte
for byte.
"""

from __future__ import annotations

from pathlib import Path

BEGIN = "# >>> dev-team-agents (managed) — regenerated by `devteam sync`, do not edit"
END = "# <<< dev-team-agents (managed)"


def _read_raw(path):
    """Read without newline translation, so CRLF survives a round trip."""
    with Path(path).open("r", encoding="utf-8", newline="") as handle:
        return handle.read()


def _write_raw(path, text):
    with Path(path).open("w", encoding="utf-8", newline="") as handle:
        handle.write(text)


def detect_newline(text, default="\n"):
    """The dominant line terminator in ``text``.

    ``Path.read_text``/``write_text`` translate newlines, so reading a CRLF
    ``.gitignore`` and writing it back rewrote **every** line to LF — a
    whole-file diff in a committed file on every bind, in exactly the Windows
    repositories most likely to need `copy` mode.
    """
    crlf = text.count("\r\n")
    lf = text.count("\n") - crlf
    if crlf and crlf >= lf:
        return "\r\n"
    if lf:
        return "\n"
    return default


def render_block(entries, newline="\n"):
    lines = [BEGIN]
    lines.extend(entries)
    lines.append(END)
    return newline.join(lines) + newline


def apply_managed_block(path, entries, create=True):
    """Write or replace the managed block in ``path``.

    Returns ``(changed, action)`` where action is ``created``, ``updated``,
    ``unchanged`` or ``removed``.
    """
    target = Path(path)

    if not target.exists():
        if not entries or not create:
            return False, "unchanged"
        target.parent.mkdir(parents=True, exist_ok=True)
        _write_raw(target, render_block(entries))
        return True, "created"

    original = _read_raw(target)
    newline = detect_newline(original)
    block = render_block(entries, newline=newline) if entries else ""
    lines = original.splitlines(keepends=True)

    start = end = None
    for index, line in enumerate(lines):
        stripped = line.rstrip("\r\n")
        if stripped == BEGIN and start is None:
            start = index
        elif stripped == END and start is not None:
            end = index
            break

    if start is not None and end is not None:
        before = "".join(lines[:start])
        after = "".join(lines[end + 1 :])
        updated = before + block + after
    else:
        # No block yet. A file whose last line lacks a newline would otherwise
        # have the first managed entry appended onto it — the exact corruption
        # a bare `>>` append produces.
        before = original
        if before and not before.endswith(("\n", "\r")):
            before += newline
        if before and not before.endswith(newline + newline):
            before += newline
        updated = before + block

    if updated == original:
        return False, "unchanged"
    _write_raw(target, updated)
    return True, "updated" if start is not None else "created"


def local_exclude_file(project_root):
    """``.git/info/exclude`` for this checkout, when it is a git repository.

    Lives here rather than in ``bind`` because two commands write that file:
    ``bind``/``sync`` regenerate its whole managed block from the artifact set, and
    ``upgrade`` has to add the two layout-2 pointers it creates without erasing the
    rest of the block. A private copy in ``bind`` made the second caller either
    import an underscore name or reimplement the linked-worktree walk below.
    """
    git_dir = Path(project_root) / ".git"
    if git_dir.is_file():
        # A linked worktree: .git is a file pointing at the real git dir.
        try:
            content = git_dir.read_text(encoding="utf-8").strip()
        except OSError:
            return None
        if content.startswith("gitdir:"):
            resolved = Path(content.split(":", 1)[1].strip())
            if not resolved.is_absolute():
                resolved = (Path(project_root) / resolved).resolve()
            common = resolved / "commondir"
            if common.is_file():
                try:
                    rel = common.read_text(encoding="utf-8").strip()
                    resolved = (resolved / rel).resolve()
                except OSError:
                    pass
            return resolved / "info" / "exclude"
        return None
    if git_dir.is_dir():
        return git_dir / "info" / "exclude"
    return None


def read_managed_entries(path):
    """The entries currently inside the managed block of ``path``."""
    target = Path(path)
    if not target.exists():
        return []
    entries = []
    inside = False
    for line in _read_raw(target).splitlines():
        stripped = line.rstrip("\r\n")
        if stripped == BEGIN:
            inside = True
            continue
        if stripped == END:
            break
        if inside:
            entries.append(stripped)
    return entries
