"""Managed ignore blocks.

Bind artifacts point at an absolute path inside one developer's store, so they
can never be committed (ADR-0007). Two files carry the ignores, for two
different audiences:

* ``.gitignore`` — the handful of project-level paths every developer on the
  project needs ignored. Committed, reviewable, short.
* ``.git/info/exclude`` — the per-provider artifacts, including one entry per
  linked skill. Local to the clone, which is exactly what a per-developer bind
  is, and keeps 150+ generated lines out of a shared file.

Both are edited only between markers; everything outside them is preserved byte
for byte.
"""

from __future__ import annotations

from pathlib import Path

BEGIN = "# >>> dev-team-agents (managed) — regenerated by `devteam sync`, do not edit"
END = "# <<< dev-team-agents (managed)"


def render_block(entries):
    lines = [BEGIN]
    lines.extend(entries)
    lines.append(END)
    return "\n".join(lines) + "\n"


def apply_managed_block(path, entries, create=True):
    """Write or replace the managed block in ``path``.

    Returns ``(changed, action)`` where action is ``created``, ``updated``,
    ``unchanged`` or ``removed``.
    """
    target = Path(path)
    block = render_block(entries) if entries else ""

    if not target.exists():
        if not entries or not create:
            return False, "unchanged"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(block, encoding="utf-8")
        return True, "created"

    original = target.read_text(encoding="utf-8")
    lines = original.splitlines(keepends=True)

    start = end = None
    for index, line in enumerate(lines):
        stripped = line.rstrip("\r\n")
        if stripped == BEGIN and start is None:
            start = index
        elif stripped == END and start is not None:
            end = index
            break

    if start is not None and end is not None:
        before = "".join(lines[:start])
        after = "".join(lines[end + 1 :])
        updated = before + block + after
    else:
        # No block yet. A file whose last line lacks a newline would otherwise
        # have the first managed entry appended onto it — the exact corruption
        # a bare `>>` append produces.
        before = original
        if before and not before.endswith("\n"):
            before += "\n"
        if before and not before.endswith("\n\n"):
            before += "\n"
        updated = before + block

    if updated == original:
        return False, "unchanged"
    target.write_text(updated, encoding="utf-8")
    return True, "updated" if start is not None else "created"


def read_managed_entries(path):
    """The entries currently inside the managed block of ``path``."""
    target = Path(path)
    if not target.exists():
        return []
    entries = []
    inside = False
    for line in target.read_text(encoding="utf-8").splitlines():
        stripped = line.rstrip("\r\n")
        if stripped == BEGIN:
            inside = True
            continue
        if stripped == END:
            break
        if inside:
            entries.append(stripped)
    return entries
