#!/bin/bash
# install-opencode.sh — Installs dev-team-agents support into a project for
# use with the opencode CLI.
#
# Idempotent. Safe to re-run. Preserves any pre-existing opencode.json(.jsonc)
# fields; only merges the `command` block generated by render-provider.sh.
#
# Prereqs:
#   · bash, python3, jq
#   · either a local clone of dev-team-agents OR a prior install.sh run that
#     places the framework at <project>/.dev-team-agents/
#
# Usage (from project root):
#   bash <path-to-dev-team-agents>/scripts/install-opencode.sh
#   bash <path-to-dev-team-agents>/scripts/install-opencode.sh --source /abs/path
#   bash <path-to-dev-team-agents>/scripts/install-opencode.sh --dry-run
#
# What it does:
#   1. Resolves source: --source flag, $DEV_TEAM_AGENTS_SOURCE env, or
#      .dev-team-agents/ (if installed via Claude install), or parent
#      directory of this script (if running from a clone).
#   2. Calls scripts/render-provider.sh --provider opencode into a staging dir.
#   3. Copies staged .opencode/agents/*.md into <project>/.opencode/agents/.
#   4. Symlinks skills/ → <project>/.opencode/skills/dev-team-agents/.
#   5. Copies the opencode plugin to <project>/.opencode/plugins/dev-team-agents.ts.
#   6. Deep-merges the rendered command snippet into <project>/opencode.json
#      (or opencode.jsonc) under the `command` key. Creates the file if absent.
#   7. Records the installed version in .dev-team-agents/VERSION (reused
#      by the existing update mechanism).

set -euo pipefail

PROJECT_ROOT="$(pwd)"
DRY_RUN=0
SOURCE_ARG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source) SOURCE_ARG="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    *) echo "install-opencode: unknown arg: $1" >&2; exit 2 ;;
  esac
done

# ── locate dev-team-agents source ─────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
candidate_sources=()
if [[ -n "$SOURCE_ARG" ]]; then candidate_sources+=("$SOURCE_ARG"); fi
candidate_sources+=("${DEV_TEAM_AGENTS_SOURCE:-}")
candidate_sources+=("$PROJECT_ROOT/.dev-team-agents")
candidate_sources+=("$SCRIPT_DIR/..")  # if running from a clone's scripts/ dir

SOURCE_DIR=""
for c in "${candidate_sources[@]}"; do
  [[ -z "$c" ]] && continue
  if [[ -f "$c/scripts/render-provider.sh" ]] && [[ -f "$c/agents/product-analyst.md" ]]; then
    SOURCE_DIR="$(cd "$c" && pwd)"
    break
  fi
done
if [[ -z "$SOURCE_DIR" ]]; then
  echo "install-opencode: ERROR: could not locate dev-team-agents source." >&2
  echo "  Looked in: ${candidate_sources[*]}" >&2
  echo "  Pass --source <path> or set DEV_TEAM_AGENTS_SOURCE to a clone's root." >&2
  exit 1
fi

echo "dev-team-agents — opencode installer"
echo "===================================="
echo "Project root:  $PROJECT_ROOT"
echo "Source dir:    $SOURCE_DIR"
if [[ $DRY_RUN -eq 1 ]]; then echo "Mode:          DRY-RUN (no writes)"; fi
echo ""

# ── prerequisites ─────────────────────────────────────────────────────
if ! command -v python3 >/dev/null 2>&1; then
  echo "install-opencode: ERROR: python3 is required." >&2; exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "install-opencode: ERROR: jq is required for opencode.json merge." >&2; exit 1
fi

# Cross-CLI plumbing (render-provider.sh + lib/{render_provider.py, tiers.json,
# tool-map.json, command-map.json, commands.json} + opencode/plugin/) is NOT
# bundled in slim Claude installs. Detect that and guide the user to the
# curl-pipe bootstrap, which fetches just these files fresh.
RENDER_SCRIPT="$SOURCE_DIR/scripts/render-provider.sh"
if [[ ! -f "$RENDER_SCRIPT" ]] || [[ ! -f "$SOURCE_DIR/opencode/plugin/dev-team-agents.ts" ]]; then
  echo "install-opencode: ERROR: source '$SOURCE_DIR' is missing cross-CLI plumbing." >&2
  echo "  This usually means the framework was installed via Claude's slim install.sh" >&2
  echo "  and the opencode-specific files were intentionally not bundled." >&2
  echo "" >&2
  echo "  To bootstrap opencode support into this project, run from its root:" >&2
  echo "    bash <(curl -sSL https://raw.githubusercontent.com/Dev-Toolbelt/dev-team-agents/main/scripts/install-provider.sh) opencode" >&2
  echo "" >&2
  echo "  Or pass --source <path-to-dev-team-agents-clone> if you have a local clone." >&2
  exit 3
fi

# ── render ────────────────────────────────────────────────────────────
STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT

bash "$SOURCE_DIR/scripts/render-provider.sh" \
  --provider opencode --source-dir "$SOURCE_DIR" --target-dir "$STAGING"

# ── write or symlink into project ────────────────────────────────────
OPENCODE_DIR="$PROJECT_ROOT/.opencode"
mkdir -p "$OPENCODE_DIR/agents" "$OPENCODE_DIR/plugins"

# 1. agents — copy (renderer already shaped frontmatter + body)
if [[ $DRY_RUN -eq 0 ]]; then
  cp -f "$STAGING/.opencode/agents/"*.md "$OPENCODE_DIR/agents/"
  echo "  + copied $(find "$OPENCODE_DIR/agents/" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ') agent files to .opencode/agents/"
fi

# 2. skills — symlink the entire skills/ directory under .opencode/skills/
SKILLS_LINK="$OPENCODE_DIR/skills/dev-team-agents"
if [[ $DRY_RUN -eq 0 ]]; then
  mkdir -p "$OPENCODE_DIR/skills"
  if [[ -L "$SKILLS_LINK" || -e "$SKILLS_LINK" ]]; then rm -rf "$SKILLS_LINK"; fi
  ln -s "$SOURCE_DIR/skills" "$SKILLS_LINK"
  echo "  + symlinked skills/ -> $SKILLS_LINK"
fi

# 3. plugin
if [[ $DRY_RUN -eq 0 ]]; then
  if [[ -f "$SOURCE_DIR/opencode/plugin/dev-team-agents.ts" ]]; then
    cp -f "$SOURCE_DIR/opencode/plugin/dev-team-agents.ts" "$OPENCODE_DIR/plugins/dev-team-agents.ts"
    echo "  + copied plugin to .opencode/plugins/dev-team-agents.ts"
  else
    echo "  ! plugin not found at $SOURCE_DIR/opencode/plugin/dev-team-agents.ts (hooks layer will not auto-wire)" >&2
  fi
fi

# 3.1 — materialize .dev-team-agents/ subset so the plugin's
# `${directory}/.dev-team-agents/scripts/hooks/...` paths resolve.
# Sourced helper mirrors the slim Claude install.
if [[ $DRY_RUN -eq 0 ]]; then
  SCRIPT_DIR_LIB="$(cd "$(dirname "${BASH_SOURCE[0]}")/lib" && pwd)"
  # shellcheck source=scripts/lib/ensure-claude-framework.sh
  source "$SCRIPT_DIR_LIB/ensure-claude-framework.sh"
  ensure_claude_framework "$PROJECT_ROOT" "$SOURCE_DIR"
  echo "  + materialized .dev-team-agents/ runtime subset (hooks/scripts/skills)"
fi

# 4. merge command snippet into project opencode.json(.jsonc)
SNIPPET="$STAGING/.opencode/commands.snippet.jsonc"
if [[ ! -f "$SNIPPET" ]]; then
  echo "install-opencode: ERROR: render-provider produced no command snippet." >&2; exit 1
fi

# Extract the JSON object from the snippet (strip leading // comments).
CLEAN_JSON=$(python3 - "$SNIPPET" <<'PY'
import json, sys, re
text = open(sys.argv[1]).read()
# strip leading // comment lines and blank lines until first '{'
lines = []
in_json = False
for ln in text.splitlines():
    if not in_json:
        if ln.lstrip().startswith('//') or not ln.strip():
            continue
        if ln.lstrip().startswith('{'):
            in_json = True
    if in_json:
        lines.append(ln)
body = "\n".join(lines)
obj = json.loads(body)
print(json.dumps(obj))
PY
)

if [[ $DRY_RUN -eq 0 ]]; then
  # We always merge into <project>/.opencode/opencode.json — opencode
  # discovers it along with any opencode.json(.jsonc) at the project root
  # (deep-merged), so we don't risk corrupting a hand-written jsonc file
  # or fighting comment syntax.
  CFG_FILE="$OPENCODE_DIR/opencode.json"
  if [[ ! -f "$CFG_FILE" ]]; then
    cat > "$CFG_FILE" <<'JSON'
{
  "$schema": "https://opencode.ai/config.json",
  "command": {}
}
JSON
    echo "  + created $CFG_FILE"
  fi
  tmp=$(mktemp)
  jq --argjson new "$CLEAN_JSON" '.command = (.command // {}) * $new' "$CFG_FILE" > "$tmp" \
    && python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$tmp" \
    && mv "$tmp" "$CFG_FILE"
  CMD_COUNT=$(echo "$CLEAN_JSON" | jq '. | length')
  echo "  + merged ${CMD_COUNT} command keys into .opencode/opencode.json (key: devteam:<name>)"
fi

# 5. record version (reuse Claude installer's VERSION file if present)
if [[ $DRY_RUN -eq 0 && -f "$SOURCE_DIR/VERSION" ]]; then
  mkdir -p "$PROJECT_ROOT/.dev-team-agents"
  cp -f "$SOURCE_DIR/VERSION" "$PROJECT_ROOT/.dev-team-agents/VERSION" 2>/dev/null || true
fi

echo ""
echo "install-opencode: done."
echo "  Next: restart opencode to load the new agents, commands, and plugin."
echo "  Slash commands: \`devteam:<name>\` registered in .opencode/opencode.json ($(jq '.command | length' "$OPENCODE_DIR/opencode.json") keys)."
if [[ $DRY_RUN -eq 1 ]]; then
  echo "  (dry-run — no files written)"
fi