#!/usr/bin/env bash
# SessionStart hook — surfaces language preference and warns when key project
# files are stale or user preferences are missing.

# Prevent WSL from loading /etc/bash.bashrc (and its start-systemd-namespace
# call) for every bash sub-process spawned by this script.
unset BASH_ENV ENV

set -uo pipefail

PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
# user-data/ (layout 1) or this project's pointers into the store (layout 2)
# are shared state that lives only in the main worktree (untracked, so a
# linked worktree never has its own copy). Resolve via --git-common-dir so a
# session started inside .worktrees/<name>/ still reads the same
# preferences.json / state / memory as the main checkout.
MAIN_REPO_ROOT="$(cd "$(git rev-parse --git-common-dir 2>/dev/null)/.." 2>/dev/null && pwd)"
[ -n "$MAIN_REPO_ROOT" ] || MAIN_REPO_ROOT="$PROJECT_ROOT"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Consolidated state (state.json) ────────────────────────────────
# shellcheck source=scripts/lib/state.sh
. "${SCRIPT_DIR}/../lib/state.sh"
# shellcheck source=scripts/hooks/lib/data-dirs.sh
. "${SCRIPT_DIR}/lib/data-dirs.sh"
# shellcheck source=scripts/hooks/lib/file-stat.sh
. "${SCRIPT_DIR}/lib/file-stat.sh"
# STATE_DIR / MEMORY_DIR are resolved BEFORE USER_DATA_DIR is assigned below —
# devteam_state_dir treats a non-empty $USER_DATA_DIR as a caller-supplied
# override, and USER_DATA_DIR here is that legacy in-project variable, not an
# override for the pointer resolution.
#
# STATE_DIR follows the `state-dir` pointer (ADR-0013): the store's
# machine-local directory once `devteam upgrade` has run, the layout-1
# .dev-team-agents/user-data/ otherwise. Only THIS directory is created below
# — never user-data/ unconditionally, which used to recreate on every session
# the exact directory an upgrade had just retired, and permanently re-tripped
# the "run devteam upgrade" nag further down because of it.
STATE_DIR="$(devteam_state_dir "$MAIN_REPO_ROOT")"
MEMORY_DIR="$(devteam_memory_dir "$MAIN_REPO_ROOT")"

# USER_DATA_DIR here names only the legacy in-project directory used as the
# preferences.json fallback below — not one of the two ADR-0013 records
# (state-dir/memory-dir above) that `devteam upgrade` relocates.
USER_DATA_DIR="${MAIN_REPO_ROOT}/.dev-team-agents/user-data"
DOCS_DIR="${PROJECT_ROOT}/docs"
# PREFS_FILE follows the resolved preference cascade projection when present
# (ADR-0008/M2 — "the one file agents read"), falling back to the legacy
# in-project preferences.json for a project that predates `devteam bind`. See
# devteam_prefs_file in data-dirs.sh. Never written to when it resolves to the
# projection — that file is generated by `devteam bind`/`sync`.
PREFS_FILE="$(devteam_prefs_file "$MAIN_REPO_ROOT")"
PREFS_DEFAULTS_FILE="${SCRIPT_DIR}/../lib/preferences-defaults.json"

mkdir -p "$STATE_DIR" 2>/dev/null || true
# Reset the once-per-session graphify-hint marker (see
# scripts/hooks/pre-tool-use/02-graphify-hint.sh) so the hint fires again at
# the start of this session instead of staying suppressed from a prior one.
rm -f "${STATE_DIR}/.graphify-hint-shown" 2>/dev/null || true
STATE_FILE="${STATE_DIR}/state.json"
# Only the layout-1 path can still hold the legacy standalone dotfiles this
# migrates — on layout 2, STATE_DIR != USER_DATA_DIR, and a leftover
# user-data/ (e.g. holding only graphify.json) must not have state.json
# written back into it.
[ "$STATE_DIR" = "$USER_DATA_DIR" ] && [ -d "$USER_DATA_DIR" ] && state_migrate_legacy "$USER_DATA_DIR"

# ── Health-check backfill ─────────────────────────────────────────
# Ensure preferences.json has every key from the canonical default schema.
# Missing keys are written with their defaults; existing user values are never
# overwritten. No-op (no write) when the file is already complete. This
# self-heals installs that predate a newly added preference key.
#
# This is a v2 mechanism and must run ONLY on the genuine layout-1 / never-bound
# fallback (devteam_prefs_is_legacy) — once a resolved projection exists, the
# M2 cascade (defaults -> global -> project, in scripts/lib/devteam/prefs.py)
# and `devteam prefs set` own preference writes. Backfilling into the
# fallback file there would write to a path nothing reads and could resurrect
# a directory ADR-0013 retired, exactly like the state_migrate_legacy guard
# above.
#
# Exception — CONSENT_KEYS. This file already exists, so its owner never saw
# the installer prompt for a field added after they installed. Backfilling the
# schema's enabled default would switch telemetry or auto-update on without
# anyone agreeing to it, so those two are backfilled as false. The user opts in
# by editing preferences.json (or re-running the installer on a fresh install).
if devteam_prefs_is_legacy "$MAIN_REPO_ROOT" \
    && [ -f "$PREFS_FILE" ] && [ -f "$PREFS_DEFAULTS_FILE" ] && command -v python3 >/dev/null 2>&1; then
    python3 - "$PREFS_FILE" "$PREFS_DEFAULTS_FILE" <<'PYEOF' 2>/dev/null || true
import sys, json
prefs_file, defaults_file = sys.argv[1], sys.argv[2]
try:
    with open(defaults_file) as f:
        defaults = json.load(f)
    with open(prefs_file) as f:
        prefs = json.load(f)
except (json.JSONDecodeError, IOError):
    sys.exit(0)
CONSENT_KEYS = ("telemetry", "auto_update")
missing = {k: v for k, v in defaults.items() if k not in prefs}
for k in CONSENT_KEYS:
    if k in missing:
        missing[k] = False
if missing:
    prefs.update(missing)
    with open(prefs_file, 'w') as f:
        json.dump(prefs, f, indent=2)
        f.write('\n')
    print("[DEVTEAM:PREFS_BACKFILL] added: " + ", ".join(sorted(missing)))
PYEOF
fi

# ── Read preferences ──────────────────────────────────────────────
STALE_DAYS=30
USER_LANG="en"
SUPPRESS="false"

if [ -f "$PREFS_FILE" ] && command -v python3 >/dev/null 2>&1; then
    # Single fork reading all three keys at once (was 3 separate python3
    # subprocess calls) — same defaults, same fallback-to-default on
    # malformed/missing file. The path goes in as argv, never into the source:
    # a quote in the project path would otherwise break (or inject into) it.
    _ALL_PREFS=$(python3 - "$PREFS_FILE" 2>/dev/null <<'PYEOF' || true
import json, sys
try:
    d = json.load(open(sys.argv[1]))
except Exception:
    d = {}
def s(v):
    return str(v).lower() if isinstance(v, bool) else str(v)
print('\x1f'.join([s(d.get('docs_stale_after_days', 30)), s(d.get('language', 'en')), s(d.get('suppress_notifications', False)), s(d.get('auto_update', False)), s(d.get('worktree_active', False))]))
PYEOF
)
    if [ -n "$_ALL_PREFS" ]; then
        IFS=$'\x1f' read -r STALE_DAYS USER_LANG SUPPRESS AUTO_UPDATE WORKTREE_ACTIVE <<< "$_ALL_PREFS"
    fi
fi
AUTO_UPDATE="${AUTO_UPDATE:-false}"
_msg() { devteam_msg "$USER_LANG" "$@"; }  # _msg <en> <pt-BR> <es>; devteam_msg is in lib/notify.sh
WORKTREE_ACTIVE="${WORKTREE_ACTIVE:-false}"

# ── Write session ID for the notifier turn counter ────────────────
state_set session_id "$(date +%s)" "$STATE_FILE"

# ── Record the commit HEAD was at when this session started ───────
# stop/_disabled-04-notifier.sh compares the current HEAD against this to
# detect a session with real turn count but zero commits — see that script.
_session_head_sha="$(git rev-parse HEAD 2>/dev/null || true)"
[ -n "$_session_head_sha" ] && state_set session_head "$_session_head_sha" "$STATE_FILE"

# ── Notification queue ────────────────────────────────────────────
# Every user-facing notice below goes to the queue the desktop app shows
# (scripts/hooks/lib/notify.sh). Initialised after session_id is written, so each
# record names this session. The `[DEVTEAM:*]` markers further down are NOT
# notifications — they are instructions to the agent and stay on stdout.
# shellcheck source=scripts/hooks/lib/notify.sh
. "${SCRIPT_DIR}/lib/notify.sh"
devteam_notify_init "$MAIN_REPO_ROOT" "$STATE_DIR" "$SUPPRESS"
TODAY_KEY="$(date +%Y-%m-%d)"
DAY_TTL=86400

# ── Update check (moved from pre-tool-use/01-check-updates.sh) ────
# Runs once per session instead of on every tool call. TTL-gated internally —
# most sessions land inside the interval window and this is a no-op fork-free
# check (see uc_ttl_fresh in update-check.sh). Errors degrade to a silent skip;
# a SessionStart hook must never block the session.
UC_LIB_FILE="${SCRIPT_DIR}/lib/update-check.sh"
if [ -f "$UC_LIB_FILE" ]; then
    # shellcheck source=scripts/hooks/lib/update-check.sh
    . "$UC_LIB_FILE"

    UC_INSTALL_DIR="${MAIN_REPO_ROOT}/.dev-team-agents"
    # last_update_check / installed_version / update_check_interval now live
    # as keys in state.json (STATE_FILE) instead of standalone dotfiles.
    # These two ETag/version caches are dot-markers too (ADR-0013) — they
    # follow STATE_DIR, not the legacy USER_DATA_DIR.
    UC_ETAG_FILE="${STATE_DIR}/.last-releases-etag"
    UC_VERSION_CACHE_FILE="${STATE_DIR}/.last-releases-version"
    UC_GITHUB_API="https://api.github.com/repos/Dev-Toolbelt/dev-team-agents"

    UC_NOW=$(uc_now_epoch)
    UC_INTERVAL_HOURS=$(uc_interval_hours "$PREFS_FILE" "$STATE_FILE")
    if ! uc_ttl_fresh "$STATE_FILE" "$UC_INTERVAL_HOURS" "$UC_NOW"; then
        if uc_setup_http; then
            state_set last_update_check "$UC_NOW" "$STATE_FILE"
            UC_LATEST=$(uc_fetch_latest "$UC_GITHUB_API" "$UC_ETAG_FILE" "$UC_VERSION_CACHE_FILE")
            UC_CURRENT=$(state_get installed_version "$STATE_FILE")
            [ -n "$UC_CURRENT" ] || UC_CURRENT="unknown"
            if uc_is_newer "$UC_CURRENT" "$UC_LATEST"; then
                export UC_SUPPRESS="$SUPPRESS"
                # Legacy .auto-update flag file is a dot-marker too — checked
                # in STATE_DIR, not USER_DATA_DIR.
                if uc_auto_update_enabled "$PREFS_FILE" "$STATE_DIR"; then
                    if uc_perform_auto_update "$UC_CURRENT" "$UC_LATEST" "$UC_INSTALL_DIR"; then
                        uc_notify updated "$(uc_message updated "$USER_LANG" "$UC_CURRENT" "$UC_LATEST")"
                    else
                        uc_notify available "$(uc_message available "$USER_LANG" "$UC_CURRENT" "$UC_LATEST")"
                    fi
                else
                    uc_notify available "$(uc_message available "$USER_LANG" "$UC_CURRENT" "$UC_LATEST")"
                fi
            fi
        fi
    fi
fi

# ── Check: preferences.json ───────────────────────────────────────
if [ ! -f "$PREFS_FILE" ]; then
    echo ""
    echo "[DEVTEAM:FIRST_TIME_SETUP]"
    echo "preferences.json not found — this appears to be your first time using dev-team-agents on this machine."
    echo ""
fi

# ── Scoped test execution reminder (always shown, every session) ──
# skills/shared/scoped-test-execution/SKILL.md is normally loaded via
# project-context's mandatory load inside /devteam:* agent routing. A
# session working outside that routing (plain main-loop work) never
# triggers that load, so the rule below is injected unconditionally here
# as the structural fix for that gap. pre-tool-use/02b-full-suite-guard.sh
# is the complementary per-command safety net.
echo ""
echo "[DEVTEAM:TEST_SCOPE_RULE] Run only tests covering touched code; full suite only on explicit user request this session (see skills/shared/scoped-test-execution/SKILL.md)."
echo ""

# ── Session banner (always shown, once per session) ───────────────
# Fallback chain for version: an installed project has installed_version in
# state.json; this repo's own self-hosted install does not, so fall back to
# the first released entry in CHANGELOG.md (the [Unreleased] header is skipped).
DT_VERSION="$(state_get installed_version "$STATE_FILE")"
if [ -z "$DT_VERSION" ]; then
    DT_VERSION="$(grep -m1 -oE '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' "${PROJECT_ROOT}/CHANGELOG.md" 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
fi
[ -n "$DT_VERSION" ] || DT_VERSION="unknown"
case "$DT_VERSION" in v*) ;; *) DT_VERSION="v${DT_VERSION}" ;; esac

DT_AUTO_UPDATE_LABEL="No"
[ "$AUTO_UPDATE" = "true" ] && DT_AUTO_UPDATE_LABEL="Yes"
DT_WORKTREE_LABEL="No"
[ "$WORKTREE_ACTIVE" = "true" ] && DT_WORKTREE_LABEL="Yes"

echo "[DEVTEAM:SESSION_BANNER]"
echo "DevTeam Agents • ${DT_VERSION} (github.com/Dev-Toolbelt/dev-team-agents)"
echo "─────────────────────────────────────────────────"
echo "Language: ${USER_LANG} | Auto Update: ${DT_AUTO_UPDATE_LABEL} | Worktree: ${DT_WORKTREE_LABEL}"
echo ""

# ── Cross-platform date diff helper ──────────────────────────────
_days_since_modified() {
    local file="$1"
    local file_ts
    file_ts=$(dt_file_mtime "$file")
    echo $(( ( $(date +%s) - file_ts ) / 86400 ))
}

_days_since_date_str() {
    local date_str="$1"
    local ts
    # An unparseable date reports 0 days (no stale warning) rather than a ts=0 epoch age.
    ts=$(dt_date_to_epoch "$date_str") || { echo 0; return; }
    echo $(( ( $(date +%s) - ts ) / 86400 ))
}

# ── Check: broken (materialized) dev-team-agents symlinks ─────────
# On Windows without Developer Mode / core.symlinks=true, git/MSYS writes
# the .claude/ links as plain text files. git-bash's `ls -la` still shows
# them as lrwxrwxrwx (MSYS emulation), but Claude Code sees files — so the
# whole dev-team silently disappears. A link is "materialized" when it
# exists, is NOT a symlink, and is NOT a directory.
_is_materialized() { [ -e "$1" ] && [ ! -L "$1" ] && [ ! -d "$1" ]; }

BROKEN_LINKS=0
_is_materialized "${PROJECT_ROOT}/.claude/agents/dev-team"   && BROKEN_LINKS=$((BROKEN_LINKS + 1))
_is_materialized "${PROJECT_ROOT}/.claude/commands/devteam"  && BROKEN_LINKS=$((BROKEN_LINKS + 1))
if [ -d "${PROJECT_ROOT}/.claude/skills" ]; then
    for _sp in "${PROJECT_ROOT}/.claude/skills"/*; do
        [ -e "$_sp" ] || continue
        _is_materialized "$_sp" && BROKEN_LINKS=$((BROKEN_LINKS + 1))
    done
fi

if [ "$BROKEN_LINKS" -gt 0 ]; then
    echo ""
    echo "[DEVTEAM:SYMLINK_BROKEN] ${BROKEN_LINKS} link(s)"
    echo "dev-team-agents links were materialized as plain files instead of symlinks"
    echo "(the Windows 'no native symlink support' condition). The dev-team is not"
    echo "loaded — /devteam:* commands, agents, and skills are invisible to Claude Code."
    echo "Fix it now by running:"
    if [ -f "$PROJECT_ROOT/.dev-team-agents/project.json" ]; then
        echo "  devteam sync"
    else
        echo "  bash .dev-team-agents/scripts/fix-symlinks.sh"
    fi
    echo "It auto-repairs when the OS allows, and otherwise prints the 3 remediation"
    echo "options to offer the user interactively. Restart Claude Code after a fix."
    echo ""
    # The marker above tells the agent; this tells the user, who otherwise only
    # notices that /devteam:* commands have vanished.
    if [ -f "$PROJECT_ROOT/.dev-team-agents/project.json" ]; then _fix="devteam sync"; else _fix="bash .dev-team-agents/scripts/fix-symlinks.sh"; fi
    devteam_notify "critical" "symlinks.broken" "$(_msg \
        "${BROKEN_LINKS} dev-team-agents link(s) are plain files, so agents, commands and skills are not loaded. Run: ${_fix}" \
        "${BROKEN_LINKS} link(s) do dev-team-agents são arquivos comuns, então agents, comandos e skills não são carregados. Execute: ${_fix}" \
        "${BROKEN_LINKS} enlace(s) de dev-team-agents son archivos comunes, por lo que no se cargan agentes, comandos ni skills. Ejecuta: ${_fix}")" \
        "$DAY_TTL" "symlinks.broken:${TODAY_KEY}"
fi

# Each check below raises its own notification, deduplicated per day: a stale
# project.md is worth one notice a day, not one per session opened that day.

# ── Check: project.md freshness ───────────────────────────────────
PROJECT_MD="${DOCS_DIR}/project.md"
if [ -f "$PROJECT_MD" ]; then
    DAYS_OLD=$(_days_since_modified "$PROJECT_MD")
    if [ "$DAYS_OLD" -gt "$STALE_DAYS" ]; then
        devteam_notify "warning" "docs.project_stale" "$(_msg \
            "docs/project.md is ${DAYS_OLD} days old — consider running /devteam:architect to refresh it." \
            "docs/project.md tem ${DAYS_OLD} dias — considere executar /devteam:architect para atualizá-lo." \
            "docs/project.md tiene ${DAYS_OLD} días — considera ejecutar /devteam:architect para actualizarlo.")" \
            "$DAY_TTL" "docs.project_stale:${TODAY_KEY}"
    fi
fi

# ── Check: session-summary.md staleness ───────────────────────────
# Portable record (ADR-0013): resolved through MEMORY_DIR, not USER_DATA_DIR.
SESSION_SUMMARY="${MEMORY_DIR}/session-summary.md"
if [ -f "$SESSION_SUMMARY" ]; then
    LAST_DATE=$(grep -m1 "^## [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}" "$SESSION_SUMMARY" \
        | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}" | head -1)
    if [ -n "$LAST_DATE" ]; then
        DAYS_SINCE=$(_days_since_date_str "$LAST_DATE")
        if [ "$DAYS_SINCE" -gt "$STALE_DAYS" ]; then
            devteam_notify "warning" "docs.session_summary_stale" "$(_msg \
                "The session summary's last entry is ${DAYS_SINCE} days old — this project may be inactive, or the summary needs updating." \
                "A última entrada do session summary tem ${DAYS_SINCE} dias — o projeto pode estar inativo, ou o resumo precisa ser atualizado." \
                "La última entrada del session summary tiene ${DAYS_SINCE} días — el proyecto puede estar inactivo, o el resumen necesita actualizarse.")" \
                "$DAY_TTL" "docs.session_summary_stale:${TODAY_KEY}"
        fi
    fi
fi

# ── Check: health check staleness ─────────────────────────────────
LAST_HEALTH_CHECK="$(state_get last_health_check "$STATE_FILE")"
if [ -n "$LAST_HEALTH_CHECK" ]; then
    HC_DATE=$(printf '%s' "$LAST_HEALTH_CHECK" | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}" | head -1)
    if [ -n "$HC_DATE" ]; then
        DAYS_SINCE_HC=$(_days_since_date_str "$HC_DATE")
        if [ "$DAYS_SINCE_HC" -gt "$STALE_DAYS" ]; then
            devteam_notify "warning" "health_check.stale" "$(_msg \
                "The last /devteam:health-check was ${DAYS_SINCE_HC} days ago — run it to catch drift (broken links, stale config, missing scripts)." \
                "O último /devteam:health-check foi há ${DAYS_SINCE_HC} dias — execute-o para detectar desvios (links quebrados, configuração desatualizada, scripts ausentes)." \
                "El último /devteam:health-check fue hace ${DAYS_SINCE_HC} días — ejecútalo para detectar desvíos (enlaces rotos, configuración desactualizada, scripts faltantes).")" \
                "$DAY_TTL" "health_check.stale:${TODAY_KEY}"
        fi
    fi
else
    # No marker at all: either never run, or an install that predates this
    # check. Only nag once things are otherwise in motion (a project.md or
    # session-summary.md already exists) — a brand-new install already gets
    # a setup flow and doesn't need a second, redundant prompt.
    if [ -f "$PROJECT_MD" ] || [ -f "$SESSION_SUMMARY" ]; then
        devteam_notify "warning" "health_check.never" "$(_msg \
            "No /devteam:health-check has been recorded for this project — run it once to verify the installation." \
            "Nenhum /devteam:health-check foi registrado para este projeto — execute-o uma vez para verificar a instalação." \
            "No se ha registrado ningún /devteam:health-check para este proyecto — ejecútalo una vez para verificar la instalación.")" \
            "$DAY_TTL" "health_check.never:${TODAY_KEY}"
    fi
fi

# ── Structure upgrade available ───────────────────────────────────
# Observable test, no JSON parsing: a bound project (project.json present)
# whose user-data/ genuinely still holds memory (not just the project-owned
# graphify.json) and whose state-dir pointer, if any, has not already moved
# outside the project — see devteam_memory_still_in_project in data-dirs.sh.
# Nothing is ever moved automatically — this only tells the user the command
# exists.
if devteam_memory_still_in_project "$MAIN_REPO_ROOT"; then
    devteam_notify "info" "layout.upgrade_available" "$(_msg \
        "This project still keeps its memory in .dev-team-agents/user-data — run \`devteam upgrade\` to move it into the store. Nothing moves until you do." \
        "Este projeto ainda guarda sua memória em .dev-team-agents/user-data — execute \`devteam upgrade\` para movê-la para o store. Nada é movido até você fazer isso." \
        "Este proyecto todavía guarda su memoria en .dev-team-agents/user-data — ejecuta \`devteam upgrade\` para moverla al store. Nada se mueve hasta que lo hagas.")" \
        "$DAY_TTL" "layout.upgrade_available:${TODAY_KEY}"
fi

exit 0
